getsentry/sentry-unity

- Assets/Sentry/Demo/Scripts/SentryTest.cs
- Assets/Sentry/Scripts/Sentry.cs
- Assets/Sentry/Scripts/SentrySdk.cs
Related to #10 as it addresses the first point.
> feat: capture event

- Assets/Sentry/Scripts/SentrySdk.cs
Resolves #26
Requires tests in the editor/baked games before merging
> fix: Only print when Debug=true

- .gitignore
- package-dev/Editor/io.sentry.unity.dev.editor.asmdef
- package-dev/README.md
- package-dev/Runtime/io.sentry.unity.dev.runtime.asmdef
- package-dev/Tests/Runtime/io.sentry.unity.dev.runtimeTests.asmdef
- package-dev/package.json
- samples/unity-of-bugs/Packages/manifest.json
- samples/unity-of-bugs/Packages/packages-lock.json
- src/Directory.Build.props
- src/Sentry.Unity.Tests/Sentry.Unity.Tests.csproj
- src/Sentry.Unity.Tests/SimpleTests.cs
- src/Sentry.Unity.sln
> package-dev structure

- .github/workflows/ci.yaml
> Run edit mode tests on CI

- src/Sentry.Unity/SentryInitialization.cs
- src/Sentry.Unity/TimeDebounceBase.cs
- src/test/Sentry.Unity.Tests/PlayModeTests.cs
> Warning debouncer added

- .github/workflows/danger.yaml
- dangerfile.js
> Add danger

- src/NuGet.config
Related to https://github.com/getsentry/sentry-unity/pull/108#issuecomment-818949784
_#skip-changelog_
> Add NuGet.config

- .github/CODEOWNERS
> Add Stefan to code owners

- CHANGELOG.md
- package/package.json
> Release package samples

- .github/workflows/ci.yaml
> ci: trigger on PR

- CHANGELOG.md
Resolves #114
/cc @semuserable @bitsandfoxes
> bump sentry-dotnet 3.3.1

- .github/workflows/ci.yaml
Just got reminded of why I hate powershell
> fix ci copy doc

- README.md
Ideas? 
I'm trying to deemphasize unity-lite now, and get folks to look to this repo now.
> update readme with dev status

- CHANGELOG.md
- dangerfile.js
Refactored, cleaned up, removed dead code and extended in accordance to #155 
> Update and extend dangerfile

- .github/workflows/ci.yml
> cache packages in CI

- .github/workflows/ci.yml
.NET 5 is already available on GHA
> dont install dotnet in ci

- .github/workflows/ci.yml
- before.Sentry.Unity.sln.targets
> restore submodules if needed

- .github/workflows/ci.yml
- Directory.Build.props
- before.Sentry.Unity.sln.targets
- test/Directory.Build.props
Removing from CI parts that dotnet build is supposed to figure out now
> fix: git submodule restore

- samples/unity-of-bugs/Packages/manifest.json
removed unused packages from the manifest
> ref: package cleanup

- CHANGELOG.md
- src/Sentry.Unity/UnityEventProcessor.cs
- test/Sentry.Unity.Tests/UnityEventExceptionProcessorTests.cs
> il2cpp remove zeroes from path

- CHANGELOG.md
- samples/unity-of-bugs/ProjectSettings/GraphicsSettings.asset
- samples/unity-of-bugs/ProjectSettings/ProjectSettings.asset
- src/Sentry.Unity/SentryUnityOptions.cs
> fix: dont set diag loger null

- CHANGELOG.md
- src/Sentry.Unity/Integrations/UnityApplicationLoggingIntegration.cs
- src/Sentry.Unity/Integrations/UnityBeforeSceneLoadIntegration.cs
- test/Sentry.Unity.Tests/UnityApplicationLoggingIntegrationTests.cs
- test/Sentry.Unity.Tests/UnityBeforeSceneLoadIntegrationTests.cs
> Breadcrumb categories added

- Directory.Build.props
- src/Sentry.Unity/SentryOptionsUtility.cs
> warning breaks ci

- .github/workflows/ci.yml
- Directory.Build.targets
- samples/unity-of-bugs/Assets/Editor/Builder.cs
- samples/unity-of-bugs/Assets/Scripts/SceneLoader.cs
> run smoke test in CI

- CONTRIBUTING.md
- Directory.Build.props
- Directory.Build.targets
- src/Sentry.Unity.Editor/Sentry.Unity.Editor.csproj
- test/Directory.Build.props
> find unity version

- Directory.Build.targets
The proposed change to make Rider work again.
Would be nice to know why it's broken in the first place tho.
> Fix: 21k+ Errors in Rider

- CHANGELOG.md
- test/Sentry.Unity.Tests/DebouncerTests.cs
- test/Sentry.Unity.Tests/UnityApplicationLoggingIntegrationTests.cs
- test/Sentry.Unity.Tests/UnityBeforeSceneLoadIntegrationTests.cs
WIP
* Debouncer tests added based on real time
* `UnityApplicationLoggingIntegration` more tests based on types
> Additional tests

- README.md
- package/README.md
- scripts/bump-version.ps1
Bumping the version on the repo updates the README:
> version in readme

- CHANGELOG.md
- src/Sentry.Unity.Editor/SentryWindow.cs
check if file exist
write file if not
just refresh the assetdatabase after writing
> Link.xml file exist check

- CHANGELOG.md
- src/Sentry.Unity/SentryOptionsUtility.cs
- test/Sentry.Unity.Tests/SentryOptionsUtilityTests.cs
> Added IsGlobalModeEnabled to SetDefaults

- .github/workflows/ci.yml
- CONTRIBUTING.md
- Directory.Build.targets
> ci: verify build output

- CHANGELOG.md
- src/Sentry.Unity/Integrations/IApplication.cs
- src/Sentry.Unity/Integrations/SessionIntegration.cs
- src/Sentry.Unity/MainThreadData.cs
- src/Sentry.Unity/SentryMonoBehaviour.cs
- src/Sentry.Unity/SentryUnityOptions.cs
- src/Sentry.Unity/SystemInfoAdapter.cs
- src/Sentry.Unity/UnityEventProcessor.cs
- test/Sentry.Unity.Tests/Stubs/TestApplication.cs
- test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
> Cache, background threads and data for UnityEventProcessor

- src/Sentry.Unity/MainThreadData.cs
- src/Sentry.Unity/Protocol/Unity.cs
- src/Sentry.Unity/SentryMonoBehaviour.cs
- src/Sentry.Unity/SystemInfoAdapter.cs
- src/Sentry.Unity/UnityEventProcessor.cs
- test/Sentry.Unity.Tests/Protocol/UnityTests.cs
- test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
> Unity protocol enriched: TargetFrameRate

- package-dev/Runtime/SentryInitialization.cs
- test/Sentry.Unity.Tests/SentryUnityOptionsExtensionsTests.cs
Welcome our ![Screenshot 2021-08-06 at 16 22 34](https://user-images.githubusercontent.com/25725783/128524787-b8c46f3c-c071-4f9c-97ee-e61fb8239a4f.png)th Play Mode test!
> unity options extension tests

- test/Sentry.Unity.Editor.iOS.Tests/NativeOptionsTests.cs
> macOS exclusive tests

- CHANGELOG.md
- src/Sentry.Unity.Editor/SentryWindow.cs
Fixes: https://github.com/getsentry/sentry-unity/issues/275
TraceSampleRate:
DSN:
> config window improvements

- .github/workflows/ci.yml
> feat: macOS support on CI

- CHANGELOG.md
- src/Sentry.Unity.Editor/SentryWindow.cs
- src/Sentry.Unity/SentryOptionsUtility.cs
> dont block init to flush

- CHANGELOG.md
The release includes the feature needed by #296
> bump dotnet sdk 3.9.0

- CHANGELOG.md
- src/Sentry.Unity/UnityEventProcessor.cs
- test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
> os.name is now os.raw_desc

- .github/workflows/release.yml
> automate release

- .github/workflows/ci.yml
> cache submodule build output

- .github/workflows/ci.yml
Previous PR showed all green checks while on check had a broken yml file.
> fix malformed yml ci file

- test.sh
> run smoke test in test script

- .craft.yml
> add symbol collector craft target

- .github/workflows/ci.yml
- src/Sentry.Unity.iOS/Properties/AssemblyInfo.cs
> cache native SDKs build output

- src/Sentry.Unity.Editor/SentryWindow.cs
- src/Sentry.Unity/Android/UnityJavaScopeObserver.cs
Trimming whitespace from DSN in Sentry window
Removed timestamp passing from C# breadcrumb to java
> Minor Android native refactor

- Directory.Build.targets
> fix: clean jar on android clean

- src/Sentry.Unity.Editor.iOS/NativeOptions.cs
- src/Sentry.Unity.Editor/SentryPreprocessBuild.cs
- src/Sentry.Unity.Editor/SentryWindow.cs
- src/Sentry.Unity/Integrations/IApplication.cs
- src/Sentry.Unity/Integrations/SceneManagerIntegration.cs
- src/Sentry.Unity/Integrations/SessionIntegration.cs
- src/Sentry.Unity/SentryBehavior.cs
- src/Sentry.Unity/SentryUnityOptions.cs
- test/Sentry.Unity.Editor.iOS.Tests/SentryXcodeProjectTests.cs
- test/Sentry.Unity.Tests/UnityLoggerTests.cs
> remove some redundant usings

- Directory.Build.targets
> better error when UnityRoot not found

- src/Sentry.Unity.Editor.iOS/Sentry.Unity.Editor.iOS.csproj
> output IOSBuildTools when it doesnt exist

- .github/workflows/ci.yml
- Directory.Build.props
- Directory.Build.targets
- samples/unity-of-bugs/Assets/Scripts/MobileNativeSupport/CPlugin.c.meta
- samples/unity-of-bugs/Assets/Scripts/MobileNativeSupport/CppPlugin.cpp.meta
- src/Directory.Build.props
- src/Sentry.Unity.Android/Sentry.Unity.Android.csproj
- src/Sentry.Unity.Editor.iOS/Sentry.Unity.Editor.iOS.csproj
- src/Sentry.Unity.Editor/Sentry.Unity.Editor.csproj
- src/Sentry.Unity.iOS/Sentry.Unity.iOS.csproj
- src/Sentry.Unity/Sentry.Unity.csproj
- test/Sentry.Unity.Android.Tests/Sentry.Unity.Android.Tests.csproj
- test/Sentry.Unity.Editor.Tests/EditorModeTests.cs
- test/Sentry.Unity.Editor.Tests/Sentry.Unity.Editor.Tests.csproj
- test/Sentry.Unity.Editor.iOS.Tests/Sentry.Unity.Editor.iOS.Tests.csproj
- test/Sentry.Unity.Tests/Sentry.Unity.Tests.csproj
- test/Sentry.Unity.iOS.Tests/Sentry.Unity.iOS.Tests.csproj
Skipping Android IL2CPP on Windows with Unity 2021 due to:
Build log of failing run: https://github.com/getsentry/sentry-unity/runs/4053064070?check_suite_focus=true
Related issue from the forum: https://forum.unity.com/threads/2019-1-0a12-cant-find-android-sdk-build-tools.599254/
```
PathTooLongException: Path is too long. Path: C:\Program Files\Unity\Hub\Editor\2021.1.26f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tempToolsDir\lib\monitor-x86\p2\org.eclipse.equinox.p2.engine\profileRegistry\DefaultProfile.profile\.data\org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions
at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x0005e] in <695d1cc93cca45069c528c15c9fdd749>:0 
at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in …
```
> CI with multiple Unity versions

- .github/workflows/ci.yml
- CHANGELOG.md
> fix release packaging

- .github/workflows/ci.yml
- Directory.Build.targets
Fix reduces the path on windows so long path errors will no longer happen for now.
> Fix long path error on Windows.

- .github/workflows/ci.yml
- Directory.Build.targets
This reverts commit 0b9413d04e2624fa478de104137f663387b94491.
> Revert "Fix long path error on Windows."

- Sentry.Unity.sln
> update VS version in sln

- .github/workflows/ci.yml
> avoid duplicating dlls in package-dev

- .github/workflows/ci.yml
- scripts/smoke-test-droid.ps1
Retry for 3 times if detected Unity timed out to initialize.
> Fix Android 27 smoke test

- test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
> fix flaky test

- .github/workflows/ci.yml
- CHANGELOG.md
CI should ignore changes to the changelog.
> fix: CI ignores CHANGELOG

- samples/unity-of-bugs/Assets/Scenes/1_Bugfarm.unity
- samples/unity-of-bugs/Assets/Scenes/2_MobileNativeSupport.unity
- samples/unity-of-bugs/Assets/Scenes/3_Transition.unity
- samples/unity-of-bugs/Assets/Scripts/MobileNativeSupport/NativeSupportButtons.cs
> fix: Sample OOM button iOS exclusive

- test/Sentry.Unity.Editor.iOS.Tests/Sentry.Unity.Editor.iOS.Tests.csproj
- test/Sentry.Unity.Tests/Sentry.Unity.Tests.csproj
> fix: Test csproj loading issues 

- test/Sentry.Unity.Editor.Tests/Sentry.Unity.Editor.Tests.csproj
Missed adding the Editor.Tests to the previous PR.
> fix: Editor.Tests.csproj

- samples/unity-of-bugs/Assets/Scenes/3_AdditionalSamples.unity
> fix: Removed dead button from samples

- samples/unity-of-bugs/Assets/Scenes/1_Bugfarm.unity
- samples/unity-of-bugs/Assets/Scenes/2_MobileNativeSupport.unity
- samples/unity-of-bugs/Assets/Scripts/AdditionalButtons.cs
- samples/unity-of-bugs/Assets/Scripts/BugFarmButtons.cs
- samples/unity-of-bugs/Assets/Scripts/MobileNativeSupport/NativeSupportButtons.cs
> fix: Sample scene switching

- samples/unity-of-bugs/Assets/Scripts/BugFarmButtons.cs
> NIT: replace System.Exception to Exception

- src/Sentry.Unity.iOS/IosNativeScopeObserver.cs
- src/Sentry.Unity.iOS/SentryNativeIos.cs
- test/Sentry.Unity.Android.Tests/SentryNativeAndroidTests.cs
- test/Sentry.Unity.iOS.Tests/SentryNativeIosTests.cs
Solves: https://github.com/getsentry/sentry-unity/issues/390
> ref: Crashed last run for iOS

- .github/labeler.yml
> meta: Add Unity platform label to PRs

- .gitignore
- samples/unity-of-bugs/Assets/Scripts/MobileNativeSupport/NativeSupportButtons.cs
> sample on console

- samples/unity-of-bugs/Assets/Scripts/MobileNativeSupport/NativeSupportButtons.cs
> remove ifdef for c plugin sample

- .github/workflows/ci.yml
> fix: Upload artifact from lowest supported Unity version on macOS runner

- .github/CODEOWNERS
> add @vaind to codeowners

- package/README.md
> feat: Added verified logo to README

- Directory.Build.targets
> fix: Restore TestRunner.dll earlier

- .gitignore
- Directory.Build.targets
- samples/unity-of-bugs/Assets/Editor/Builder.cs
- samples/unity-of-bugs/Assets/Scripts/SmokeTester.cs
> SmokeTest fixes & improvements

- .github/workflows/ci.yml
> ci: align job names

- CHANGELOG.md
> fix: Changelog

- .github/workflows/update-deps.yml
> feat: Added deploy key

- .github/workflows/ci.yml
- .github/workflows/sdk.yml
- before.Sentry.Unity.sln.targets
some small changes and cleanups
> CI speedup

- .github/workflows/sdk.yml
> ci: change retention policy on the main branch

- CHANGELOG.md
> fix heading changelog

- src/Sentry.Unity.Android/SentryJava.cs
> fix: android java close() call

- Directory.Build.targets
- src/Sentry.Unity.Native/SentryNativeBridge.cs
- src/Sentry.Unity/Integrations/IApplication.cs
> chore: Removed redundant slashes

- samples/unity-of-bugs/ProjectSettings/ProjectSettings.asset
> chore: disable armv7a android target in the sample

- CHANGELOG.md
> bump dotnet 3.15.0

- .github/workflows/ci.yml
> CI: Reenable PR trigger after GH actions issue has been resolved

- .github/workflows/sdk.yml
- CHANGELOG.md
- Directory.Build.targets
- src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
- test/Scripts.Tests/package-release.zip.snapshot
> chore: include windows sentry.pdb in the package

- src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
> chore: Using SentryPackageInfo for package name

- CHANGELOG.md
> fix: Updated changelog

- README.md
> readme: update video

- src/Sentry.Unity.Editor/ConfigurationWindow/OptionsConfigurationTab.cs
> chore: Tweaked info text in Editor Window

- .github/ISSUE_TEMPLATE/bug.md
I think this might become even more relevant in the future.
> feat: Added installation mode for bug reports

- src/Sentry.Unity/UnityEventProcessor.cs
- test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
> fix: align boolean tag values

- src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs
- src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs
- src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs
- src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
- src/Sentry.Unity.Editor/SentryCliOptions.cs
- src/Sentry.Unity.Editor/SentryScriptableObject.cs
- src/Sentry.Unity/SentryUnityOptionsExtensions.cs
- test/Sentry.Unity.Editor.Tests/Android/AndroidManifestConfigurationTests.cs
- test/Sentry.Unity.Editor.Tests/Android/DebugSymbolUploadTests.cs
- test/Sentry.Unity.Editor.Tests/SentryScriptableObjectTests.cs
- test/Sentry.Unity.Tests/SentryUnityOptionsExtensionsTests.cs
It was getting a bit hard to follow what was enabled/disabled and why.
> chore: Improved native options checks and logging

- .github/workflows/ci.yml
> Update assembly alias to 0.4.3

- samples/unity-of-bugs/Packages/manifest.json
- samples/unity-of-bugs/Packages/packages-lock.json
> chore: update sample dependencies

- CHANGELOG.md
- samples/unity-of-bugs/Assets/Scenes/3_AdditionalSamples.unity
- samples/unity-of-bugs/Assets/Scripts/AdditionalButtons.cs
- src/Sentry.Unity/Integrations/ANRIntegration.cs
- src/Sentry.Unity/SentryUnityOptions.cs
- src/Sentry.Unity/SentryUnityOptionsExtensions.cs
- src/Sentry.Unity/WebGL/SentryWebGL.cs
- test/Sentry.Unity.Tests/AnrDetectionTests.cs
- test/SharedClasses/TestLogger.cs
* closes #708 
* https://sentry.io/organizations/sentry-sdks/issues/3314229346/events/e83f4535c2294197b393000c2a09452d/?project=5439417
> Application-not-responding detection

- CONTRIBUTING.md
> fix: Typo CONTRIBUTING.md

- README.md
- package/README.md
> readme: drop forum for discussions

- src/Sentry.Unity.Android/SentryJava.cs
- src/Sentry.Unity/SystemInfoAdapter.cs
Rider keeps complaining about 'em. #skip-changelog
> chore: Comments

- src/Sentry.Unity.Editor/SentryUnityVersion.cs
> fix: Added missing import

- CHANGELOG.md
forgot a changelog for the wizard #780 
> chore: wizard changelog

- CHANGELOG.md
- src/Sentry.Unity/Default/UnknownPlatform.cs
> feat: Disable AutoSessionTracking on unknown platforms

- .github/workflows/update-deps.yml
- modules/sentry-cli.properties
- scripts/download-sentry-cli.ps1
> ci: auto-update CLI

- CHANGELOG.md
- src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs
Resolves https://github.com/getsentry/sentry-unity/issues/838
> fix: Disabling native Android ANR

- samples/unity-of-bugs/Assets/Scenes/4_ThreadedSamples.unity
- samples/unity-of-bugs/Assets/Scripts/ThreadingSamples.cs
> chore: add BG thread executor to the sample

- CHANGELOG.md
- src/Sentry.Unity.Editor/ConfigurationWindow/Wizard.cs
Wizard now auto selects organization and project if there is only one option available.
> fix: Wizard auto select

- CHANGELOG.md
> fix: Changlog

- test/Scripts.Integration.Test/common.ps1
> fix: Symbol upload test 2020

- src/Sentry.Unity/Il2CppEventProcessor.cs
- src/Sentry.Unity/SentryUnityOptions.cs
- src/Sentry.Unity/UnityEventProcessor.cs
> feat: Adding il2cpp as integration to SdkVersion

- samples/unity-of-bugs/Assets/Scenes/2_NativeSupport.unity
- samples/unity-of-bugs/Assets/Scripts/NativeSupport/CPlugin.c
- samples/unity-of-bugs/Assets/Scripts/NativeSupport/NativeButtons.cs
- src/Sentry.Unity.Editor/ConfigurationWindow/SentryEditorWindowInstrumentation.cs
- src/Sentry.Unity/Il2CppEventProcessor.cs
- src/Sentry.Unity/NativeUtils/CFunctions.cs
- src/Sentry.Unity/ScriptableSentryUnityOptions.cs
- src/Sentry.Unity/SentryUnityOptionsExtensions.cs
- test/Scripts.Integration.Test/integration-test.ps1
- test/Scripts.Integration.Test/update-sentry.ps1
Tested (inspected debug logs) manually on:
* Windows Unity 2020, 2021, 2022
* Linux Unity 2021
* Android Unity 2021
* iOS Unity 2021
closes #897 
--------------------
Outdated:
* before: https://sentry.io/organizations/sentry-sdks/issues/3441819954/events/52c89fbf31014683954a7f7477829da7/?project=5439417
* after: https://sentry.io/organizations/sentry-sdks/issues/3441819954/events/d25ae586cd7c4a768c8564d43b7a0b1a/?project=5439417
partial diff:
> IL2CPP debug images, fixes and tests

- CONTRIBUTING.md
> fix: Update Contributing.md

- CHANGELOG.md
- src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
- src/Sentry.Unity.Editor/SentryCli.cs
- src/Sentry.Unity/Il2CppEventProcessor.cs
> Fix CLI file upload limit

- .github/workflows/ci.yml
- scripts/ci-env.ps1
- test/Scripts.Integration.Test/Editor/Builder.cs
> feat: Adding Unity 2022 to CI

- .github/workflows/update-deps.yml
> fix: Added Unity 2022 as dependency

- dangerfile.js
I've made some changes to dangerJS integration when copying to Unreal.
e.g. `#skip-changelog` wouldn't be necessary here because the PR starts with "ci:"
> ci: dangerfile improvements

- CHANGELOG.md
> fix: Misplaced Changelog entry

- test/Sentry.Unity.Tests/UnityEventScopeTests.cs
> fix: Eventrprocessor Test

- test/Scripts.Integration.Test/common.ps1
> fix: Symbol upload - Special cased 2020

- package-dev/Runtime/SentryInitialization.cs
> fix: Check for `TraceSampleRate` before creating a Startup Transaction

- test/Scripts.Integration.Test/common.ps1
fixed now: https://github.com/getsentry/sentry-unity/actions/runs/3292031501/jobs/5426921882#step:12:1949
> chore: fix android smoke test symbol-upload checks

- src/Sentry.Unity.Editor/ConfigurationWindow/CoreTab.cs
> chore: Add experimental tag

- test/Scripts.Integration.Test/common.ps1
> chore: Android symbol upload smoketest

- CONTRIBUTING.md
Updated the `Building Java SDK` part.
> chore: Updated CONTRIBUTING.md

- test/Sentry.Unity.Tests/IntegrationTests.cs
- test/Sentry.Unity.Tests/ScreenshotAttachmentContentTests.cs
- test/Sentry.Unity.Tests/UnityEventScopeTests.cs
> fix: Closing the SDK on `TearDown`

- src/Sentry.Unity/Integrations/AnrIntegration.cs
Error in converting the Timespan into [ms]
> fix: ANR total ms instead of ms

- Directory.Build.targets
- scripts/create-sentry-cli-options.ps1
> chore: Dev-Target for creating sample CLI options asset

- CHANGELOG.md
- package-dev/Runtime/SentryIntegrations.cs
- src/Sentry.Unity.Editor/ConfigurationWindow/CoreTab.cs
- src/Sentry.Unity.Editor/ScriptableSentryUnityOptionsEditor.cs
- src/Sentry.Unity/ScriptableSentryUnityOptions.cs
- src/Sentry.Unity/SentryUnityOptions.cs
There was no way to opt out of any individual integration.
> feat: Added Performance Integration options to window

- CONTRIBUTING.md
- test/Sentry.Unity.Tests/IntegrationTests.cs
- test/Sentry.Unity.Tests/SentryUnityTests.cs
- test/Sentry.Unity.Tests/SessionIntegrationTests.cs
Follow-up on: https://github.com/getsentry/sentry-unity/pull/1166
> chore: Updated the DSN to new proj

- package-dev/Runtime/SentryInitialization.cs
> fix: Missing check for startup traces

- test/Scripts.Integration.Test/common.ps1
> chore: Updated expected symbols for Android

- .github/workflows/ci.yml
- .github/workflows/sdk.yml
- .github/workflows/update-deps.yml
- scripts/unity-utils.ps1
- test/Scripts.Integration.Test/Editor/Builder.cs
- test/Scripts.Integration.Test/add-sentry.ps1
- test/Scripts.Integration.Test/common.ps1
- test/Scripts.Integration.Test/integration-test.ps1
You can review individual commits - they're (mostly) self-contained
> ci: speed & stability improvements

- CHANGELOG.md
- src/Sentry.Unity/Integrations/UnityBadGatewayExceptionFilter.cs
- src/Sentry.Unity/SentryUnityOptions.cs
- test/Sentry.Unity.Tests/UnityBadGatewayExceptionFilterTests.cs
Resolves https://github.com/getsentry/sentry-unity/issues/1287
> fix: Filter `Bad Gateway exceptions` of type `Exception`

- src/Sentry.Unity.Editor/ConfigurationWindow/CoreTab.cs
> fix: Debounce as toggle group in window

- CHANGELOG.md
> fix changelog version info

- CHANGELOG.md
> fix changelog entry to version

- src/Sentry.Unity.Editor/ConfigurationWindow/CoreTab.cs
> chore: Remove duplicate debounce checkbox

- scripts/ci-docker.sh
> chore: `GameCI` to `2.0.0`

- CHANGELOG.md
> remove chore from changelog

- .github/workflows/release.yml
> fix: Added `merge_target` for releasing

- CHANGELOG.md
- package-dev/Tests/Runtime/SentrySceneTracingIntegrationTests.cs
> Fix Changelog

- src/Sentry.Unity/ScreenshotAttachment.cs
Looks like just setting the capacity is flaky.
> fix: Screenshot in CI

- LICENSE.md
#skip-changelog 
cc @gavin-zee
> date range to license - 2021-2024

- CHANGELOG.md
- src/Sentry.Unity.Android/JniExecutor.cs
> do not set exception on task failure, improve single call enforcement

- .github/workflows/update-deps.yml
There have been changes to the download page. This should fix the updater CI
> ci: fix unity update script

- .gitignore
> chore: Updated `.gitignore`

- CHANGELOG.md
> fix: Updated CHANGELOG.md

- .github/workflows/ci.yml
- Directory.Build.props
- Directory.Build.targets
- scripts/ci-env.ps1
- src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs
- src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs
- src/Sentry.Unity.Editor/ConfigurationWindow/AdvancedTab.cs
- src/Sentry.Unity.Editor/Il2CppBuildPreProcess.cs
- src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
- test/Scripts.Integration.Test/Editor/Builder.cs
- test/Scripts.Integration.Test/common.ps1
- test/Scripts.Integration.Test/modify-gradle-project.ps1
- test/Sentry.Unity.Editor.Tests/Android/DebugSymbolUploadTests.cs
> chore: Add Unity 6 to CI

- scripts/build-and-alias.ps1
> chore: Helper script for aliased builds

- .github/workflows/ci.yml
> fix: CI docker login

- .github/workflows/ci.yml
> chore: Give names to CI steps

- .github/workflows/ci.yml
- test/Scripts.Integration.Test/Editor/Builder.cs
- test/Sentry.Unity.Tests/IntegrationTests.cs
> fix: Builder

- .github/workflows/ci.yml
> fix: Ignore pre-build failure in CI

- .github/workflows/ci.yml
> fix: Don't run smoke test in main CI

- .github/workflows/ci.yml
> fix: Build iOS project on main

- CHANGELOG.md
- Directory.Build.targets
> fix: link sentry native against static windows CRT

- scripts/ci-env.ps1
> Update to Unity 6.0.25f1

- .github/workflows/update-deps.yml
> chore: Added Unity 6 to the deps updater

- README.md
> blogs to readme

- test/Scripts.Integration.Test/Editor/Builder.cs
To combat that flake happening on Linux.
> fix: Setting graphics settings for Linux in CI

- CHANGELOG.md
> chore: Updated `CHANGELOG.md` for `3.0.0`

- test/Scripts.Integration.Test/Editor/Builder.cs
Relates to https://github.com/getsentry/sentry-unity/issues/249
> feat: Set stripping level to `High` in CI

- CHANGELOG.md
> fix CHANGELOG remove dupe
