getsentry/sentry-unity

Assets/Sentry/Scripts/Sentry.cs, Assets/Sentry/Scripts/SentrySdk.cs
The Unity SDK has no capacity for sending anything other than an error, so I've modified the `CaptureMessage` flow to be a less serious level.
=> feat: messages "info" level instead of "error"

Assets/Sentry/Scripts/SentrySdk.cs
We encountered an issue where Unity would throw the error `UnityException: get_time can only be called from the main thread.` in `HandleLogCallback`. Turns out that even with the lock object, `Time.time` can't be called off the main thread. Switching `logMessageReceivedThreaded ` with `logMessageReceived` fixes the issue.
=> feat: fixed issue where Time.time was called on non-main threads

README.md
Just doing my civic duty, saw this when I came across the SDK for the first time.
=> Typo in method AddBreadcrumb

Assets/Sentry/Scripts/SentrySdk.cs
It will help fix the case when we try to log error.
For example when we call ScheduleException with "Error test" as condition it will call IndexOutOfBoundsException here(SendrySdk.cs:177):
`        var exc = condition.Split(new char[] { ':' }, 2); `
`        var excType = exc[0];`
`        var excValue = exc[1].Substring(1); // strip the space`
=> Handle LogType other than Exception

.gitmodules
Allows either HTTPS or SSH recursive cloning to work without switching protocols.
=> use relative URL for sentry-dotnet submodule

.github/workflows/ci.yaml
Related to #75
I don't understand this step:
> Bump Unity package version from package.json in that new folder
What should be the version be bumped to? Shouldn't it be done locally, not on CI, when running the bump script? It can bump both the `Directory.Build.props` version as well as `package.json` version.
=> Prepare release artifact on CI

CHANGELOG.md, src/NuGet.config, src/Sentry.Unity/UnityEventProcessor.cs, src/test/Sentry.Unity.Tests/PlayModeTests.cs
=> Strip zeroes for ill2cpp builds

CHANGELOG.md, src/Sentry.Unity/UnityEventProcessor.cs, src/test/Sentry.Unity.Tests/PlayModeTests.cs
* check version numbers and naming for package too. I guess the version should be different
* removed nullability for `SentryEvent` and `Sdk` based on `dotnet Sentry SDK`, it's still on `ISentryEventProcessor`, but from usage perspective it's **not** nullable
closes #96
=> Proper sdk name reporting for sentry event; test

.github/workflows/ci.yaml
The idea here is to use the `README.md` from the 'package template directory'
Possibly better idea is to just copy all files from `package` since it's supposed to be the template directory now (i.e: All files in it will go into the package as-is)
=> use readme from package dir

CHANGELOG.md
=> bump dotnet 3.3.4

.github/workflows/ci.yaml
This build log is huge:
Also, shaves off a whole **16ms** off of the build time 😎
=> build log only on failure

.github/workflows/ci.yaml, CHANGELOG.md
This is just a temporary thing to test if the build-times are indeed sped up by caching the build. Proper key/naming follows if it works.
=> Ci build caching

.github/workflows/ci.yaml
- CHANGELOG.md & LICENSE.md get copied from the root
- .meta files live inside package/
So when we copy them into package-release we need to fetch their meta files too.
=> Fix: Copy missing .meta files from package/

src/Sentry.Unity.Editor/SentryTestWindow.cs, src/Sentry.Unity.Editor/SentryWindow.cs, src/Sentry.Unity/Properties/AssemblyInfo.cs, src/Sentry.Unity/SentryInitialization.cs, src/Sentry.Unity/UnitySentryOptions.cs
We check for the config file before we try to load them.
If not found -> Print out "What to do" for the user and skip Sentry initilization.
=> #119 check for options file and disable logger if not found

src/Sentry.Unity/Sentry.Unity.csproj
`dotnet clean` before:
`dotnet clean` after:
This is useful for development so no changelog entry
=> clean removes all asms

CHANGELOG.md, src/Sentry.Unity.Editor/SentryWindow.cs, src/Sentry.Unity/SentryUnityOptions.cs, test/Sentry.Unity.Tests/TestSentryOptions.json, test/Sentry.Unity.Tests/UnitySentryOptionsTest.cs
The .NET SDK already has an option called `DiagnosticLogger` removing the one defined here in favor of that
=> fix: diagnostic logger rename

Directory.Build.props
CI didn't catch this because it takes a path as an argument.
=> fix: Windows unity invocation by msbuild

src/Sentry.Unity/SentryUnity.cs, src/Sentry.Unity/SentryUnityOptions.cs
When the sdk gets configured programmatically we attach the logger just before we initialize the SDK itself.
=> Fix: Programmatic config - logger attachment

package-dev/Runtime/io.sentry.unity.dev.runtime.asmdef
Try to silence "Assembly for Assembly Definition File 'Packages/io.sentry.unity.dev/Runtime/io.sentry.unity.dev.runtime.asmdef' will not be compiled, because it has no scripts associated with it."
=> try to silence the warning

CHANGELOG.md, src/Sentry.Unity/UnityEventProcessor.cs, test/Sentry.Unity.Tests/UnityEventExceptionProcessorTests.cs
closes https://github.com/getsentry/sentry-unity/issues/165
=> SentryEvent.ServerName forced to 'null'

CHANGELOG.md, src/Sentry.Unity/SentryUnity.cs, src/Sentry.Unity/UnityEventProcessor.cs, test/Sentry.Unity.Tests/IntegrationTests.cs
Release should be` productName@version` if it's not overwritten by the user.
=> Fix: Add product name to release as default

CHANGELOG.md, src/Sentry.Unity/SentryUnity.cs, test/Sentry.Unity.Tests/IntegrationTests.cs
If for some reason the product name is missing / just whitespace we just use the version as release.
=> Fix: Fallback for missing/empty product name

CHANGELOG.md, src/Sentry.Unity.Editor/SentryWindow.cs, src/Sentry.Unity/SentryOptionsUtility.cs, src/Sentry.Unity/SentryUnityOptions.cs
closes https://github.com/getsentry/sentry-unity/issues/217
I decided to force `Auto` if you configure from sentry window. We can differentiate between scripting backends with the following code
```csharp
PlayerSettings.GetScriptingBackend(EditorUserBuildSettings.selectedBuildTargetGroup) == ScriptingImplementation.IL2CPP
```
but it's available only in `Unity.Editor.dll`. We could do that logic not on options level, but on window level itself.
Which path should we take?
**PS**. Please notice, I didn't include tests as I'm trying to understand which approach we take.
=> Force 'Auto' from sentry window

CHANGELOG.md, src/Sentry.Unity/Integrations/IApplication.cs, src/Sentry.Unity/Protocol/Unity.cs, src/Sentry.Unity/SentryUnityOptions.cs, src/Sentry.Unity/UnityEventProcessor.cs, test/Sentry.Unity.Tests/Protocol/UnityTests.cs, test/Sentry.Unity.Tests/Stubs/TestApplication.cs, test/Sentry.Unity.Tests/Stubs/TestHub.cs, test/Sentry.Unity.Tests/UnityEventExceptionProcessorTests.cs
closes https://github.com/getsentry/sentry-unity/issues/49
~WIP~
=> Unity protocol

src/Sentry.Unity/UnityEventProcessor.cs
I decided not to call `.ToLower()`, as in order to do so we need to convert `bool` to `string` first and then call `.ToLower()`.
Benefits: less allocations.
=> Lowercase true or false for tag value

CHANGELOG.md, src/Sentry.Unity/Json/JsonSentryUnityOptions.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, src/Sentry.Unity/SentryOptionsUtility.cs, src/Sentry.Unity/SentryUnity.cs
TryAttachLogger got called too early and default `debug = false` so no logging, at all.
=> Logger now attaching again 

src/Sentry.Unity/Integrations/IApplication.cs, src/Sentry.Unity/Integrations/SessionIntegration.cs, src/Sentry.Unity/SentryMonoBehaviour.cs, src/Sentry.Unity/SentryOptionsUtility.cs, test/Sentry.Unity.Tests/IntegrationTests.cs, test/Sentry.Unity.Tests/SentryMonoBehaviourTests.cs, test/Sentry.Unity.Tests/SessionIntegrationTests.cs, test/Sentry.Unity.Tests/Stubs/TestApplication.cs
Unit-Tests for OnApplicationPause/Focus
One puny integration test to make sure SentryMonoBehaviour gets created.
=> SentryMonoBehaviour Tests

src/Sentry.Unity/UnityEventProcessor.cs
Introduced a bug with previous PR. Missed deferred call for `UnityEventProcessor`.
Found it via a profiler when Sentry is disabled :)
=> SentryMonoBehaviour deferred call

CHANGELOG.md
Mainly because of https://github.com/getsentry/sentry-dotnet/pull/1105
With this addition we should see sessions ending as `Abnormal` if there wasn't a clean exit: at least the session being put on the backgrund (aka: paused).
=> feat/dotnet 3.8.0 persistent session

src/Sentry.Unity/MainThreadData.cs, src/Sentry.Unity/SystemInfoAdapter.cs, src/Sentry.Unity/UnityEventProcessor.cs, test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
=> DeviceModel set lazily (~ -20ms Sentry init); tests

CHANGELOG.md, src/Sentry.Unity/UnityLogger.cs
To better support users who configure console to print a single line which currently shows like this:
Looks like this at the end:
=> log in single line

CHANGELOG.md, samples/unity-of-bugs/ProjectSettings/GraphicsSettings.asset
Mainly because of:
> Don't cancel cache flushing on init #1139
https://github.com/getsentry/sentry-dotnet/pull/1139
=> bump dotnet 3.8.3

CHANGELOG.md, samples/unity-of-bugs/Assets/Plugins/NativeExample.c, samples/unity-of-bugs/Assets/Plugins/NativeExample.c.meta, samples/unity-of-bugs/Assets/Scripts/BugFarm.cs, samples/unity-of-bugs/ProjectSettings/GraphicsSettings.asset
Tested locally and:
* in the editor it prints; 
* Built an IL2CPP macOS player and it crashed as expected.
=> native crash in sample

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/NativeOptions.cs
We now pass the level as string to the native options.
=> fix: Passing Sentry diagnostic level to iOS native layer

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs
Because we moved SentryInitialization out of our DLL to compile with the game and it was not covered by our link.xml the code stripper just gets rid of ot.
=> fix: SentryInitialization prevents codestripping of Init

CHANGELOG.md
Cocoa SDK Bugfix bumb (and it's nicer version number than a 7.2.0.beta7)
=> feat: Bump Cocoa SDK to 7.2.2

.github/workflows/ci.yml, scripts/pack.ps1
PR #316 broken packaging which tries to copy files that don't exist.
This PR fixes that (by removing the two copy commands) and also moves the script to a local file so we can test things locally more easily
=> fix: ci and pack

.github/workflows/ci.yml
The goal is to have as many operations as possible that don't requires running Unity, outside the steps that lock the license.
=> reduce license usage

.gitignore, CHANGELOG.md, package-dev/Editor/Sentry.Unity.Editor.dll.meta, package-dev/Editor/iOS/Sentry.Unity.Editor.iOS.dll.meta, package-dev/Runtime/Sentry.dll.meta, package-dev/Tests/Editor/Sentry.Unity.Editor.Tests.dll.meta, package-dev/Tests/Editor/Sentry.Unity.Editor.iOS.Tests.dll.meta
Fixes: https://github.com/getsentry/sentry-unity/issues/309
The *dll.meta files allow us fine-grained control of which DLLs do what on which platform.
So all of our iOS related DLL are exclusive to OSX.
I added all of our dll metas in this PR because this issue keeps coming up and I don't want to manually exclude each and every file.
=> fix: Resolving iOS reference on Windows

package-dev/Plugins/iOS/SentryNativeBridge.m, src/Sentry.Unity.iOS/IosNativeScopeObserver.cs
Added `CrashedLastRun` to bridge so the .NET layer can properly deal with sessions that crashed on the native layer. 
=> feat: iOS scope sync - added 'crashed last run'

test/Sentry.Unity.Editor.Tests/AndroidManifestConfigurationTests.cs
Upon package import users get hit with an API update prompt followed by an error in the console: 
`Failed to resolve assembly: 'Sentry'`.
Apparently, editor tests can't deal with test cases containing types from different assemblies?
<details><summary>Errorlog</summary>
```
Unable to update following assemblies:Packages/io.sentry.unity.dev/Tests/Editor/Sentry.Unity.Editor.Tests.dll (Name = Sentry.Unity.Editor.Tests, Error = 131) (Output: /var/folders/49/tcrc4c010s5dzxspqp6f8nbm0000gn/T/tmp17cd92f3.tmp)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Sentry, Version=3.9.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0'
at …
```
=> fix: Editor.Tests.dll failed to resolve Sentry

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs, test/Sentry.Unity.Editor.iOS.Tests/SentryXcodeProjectTests.cs
Fixes: https://github.com/getsentry/sentry-unity/issues/304
Unity copies the `.framework` and our `bridge.m` in any case. But with invalid options, we bail too soon and the Xcode project gets left in a broken state.
=> fix: Properly embedded iOS native support

src/Sentry.Unity.Editor/ScriptableSentryUnityOptionsEditor.cs, src/Sentry.Unity.Editor/SentryWindow.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs
Default values for new options (i.e. when users upgrade) should be set.
Added a minor config window refactor: Core - Enrichment - Transport - Advanced 
=> fix: Default values for new options

CHANGELOG.md, samples/unity-of-bugs/Assets/Scenes/1_BugfarmScene.unity, samples/unity-of-bugs/Assets/Scripts/BugFarm.cs, samples/unity-of-bugs/Assets/Scripts/CPlugin.c, samples/unity-of-bugs/Assets/Scripts/CPlugin.c.meta, samples/unity-of-bugs/Assets/Scripts/CppPlugin.cpp, samples/unity-of-bugs/Assets/Scripts/CppPlugin.cpp.meta, samples/unity-of-bugs/Assets/Scripts/ObjectiveCPlugin.m, samples/unity-of-bugs/Assets/Scripts/ObjectiveCPlugin.m.meta, samples/unity-of-bugs/ProjectSettings/GraphicsSettings.asset, samples/unity-of-bugs/ProjectSettings/ProjectSettings.asset
In both new samples I wasn't able to get a symbolicated stack trace properly. Even though I ran `sentry-cli` on the directory I configured Unity to create the xcode project and also on the original Unity project (so it can get anything under Temp). In both situations I got:
It could symbolicate frames from the SDK itself (since the `.framework` is copied to the xcode project and `sentry-cli` found it there) but I didn't find the `UnityFramework.framework`.
Sounds like it's something we need to find out and properly document so users don't get confused.
In any case, here we have 2 more samples: C++ Exceptions and C++ segfault
The Objective-C example requires an additional configuration which requires documenting: https://github.com/getsentry/sentry-unity/issues/343
=> c, obj-c and cpp samples

src/Sentry.Unity.Android/AndroidJavaScopeObserver.cs, src/Sentry.Unity.Android/BreadcrumbExtensions.cs
Resolves #345
* Not storing the reference of any JNI object
* Calling `AndroidJNI.AttachCurrentThread();` before any call to Java layer
Not adding to the changelog since this feature wasn't released yet.
=> fix android jni threading

.github/workflows/ci.yml, CHANGELOG.md, samples/unity-of-bugs/Packages/manifest.json, samples/unity-of-bugs/Packages/packages-lock.json, samples/unity-of-bugs/ProjectSettings/ProjectVersion.txt
Added a changelog entry since this could affect how building/testing and packaging is done.
=> Unity 2019.4.30f1

CONTRIBUTING.md
Unfortunately, the setup for the Java SDK requires some additional manual steps.
Known issue: The Java SDK seems to require some specific android build tool version. We need a way to pull them from somewhere instead of "hardcoding" it here. It'll get outdated really quickly.
=> fix: Updated CONTRIBUTING.md for Java SDK setup

CHANGELOG.md
The version bump brings the isCrashedLastSession feature to the Android native support.
This completes our feature requirements for a release!
=> chore: Android SDK 5.2.1

.craft.yml
=> fix: Craft - Exclude symbols for github target

Directory.Build.props
Rider does not deal very well building with overriding the TargetFrameworks even tho `ResetTargetFrameworks` gets called.
=> fix: Set default TargetFramework to netstandard2.0

Directory.Build.targets
The Gradle daemon is designed to speed up subsequent builds. But on GitHub action it runs only once and the daemon is killed (all processes spawned during the build are killed). 
Trying to hunt down the reason why the builds are hanging even after all steps completed. Including the final:
=> disable gradle daemon

Directory.Build.targets
These warnings are dealt with through `sentry-java`. It becomes very noisy on our build logs here and sort of out of our control
=> disable gradle warnings

CHANGELOG.md, package-dev/Editor/sentry-cli/checksums.sha, scripts/download-sentry-cli.sh
Adding sentry-cli for convenience for now. And because we'll need it for the upcoming automated symbols upload.
=> feat: Added sentry-cli to package

.github/workflows/ci.yml, Directory.Build.targets
Fix reduces the path on windows so long path errors will no longer happen during Github Actions tests for now.
=> Fix long path error on Windows build.

.github/workflows/ci.yml, Directory.Build.targets, samples/unity-of-bugs/ProjectSettings/ProjectSettings.asset, scripts/smoke-test-droid.ps1
Add smoke tests with Android emulators.
Tests will run only if the main tests are completed on all devices to allow better usage of job parallelism.
NOTE: In addition to the test, the IL2CPP apk required to support the X86 ABI in order to run the tests.
Additionally, the tests only ran on macOS due to Virtualization limitations on Github being exclusively supported on the macOS host.
=> Add Android Devices Test on mac-latest.

.github/workflows/ci.yml, .gitignore, CHANGELOG.md, package-dev/assembly-alias.ps1, src/Directory.Build.props, src/Sentry.Unity/Sentry.Unity.csproj, test/Sentry.Unity.Tests/Sentry.Unity.Tests.csproj
=> perform assembly alias

test/Sentry.Unity.Tests/DebouncerTests.cs
Tracked by: https://github.com/getsentry/sentry-unity/issues/335
They are just too unreliable. 
And debouncing is disabled by default.
=> fix: Disabling flaky debounce tests

samples/unity-of-bugs/Assets/Scripts/SmokeTester.cs
We need to refactor things so that we can resume the init bits from smoke-test and SentryInitialization
@lucas-zimerman 
=> fix: Smoke test include native SDK init

src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, src/Sentry.Unity.Editor.iOS/Sentry.Unity.Editor.iOS.csproj, src/Sentry.Unity.Editor/Properties/AssemblyInfo.cs
During development, we append `.dev` to the package name. That has to be taken into account e.g. we copy Sentry.framework to the generated Xcode project and the package name is part of the path.
The Android symbols upload introduced a static PackageInfo so there is no need to keep this inside the Editor.iOS project.
=> fix: Editor.iOS uses PackageInfo for package name

.github/workflows/ci.yml, scripts/smoke-test-droid.ps1
* Upload screenshots if test failed.
* Increased timeout by 15 seconds.
* Fix PS log if test timed out
* Removed Sentry/Unity filter from logcat.
* Increased Android ram to 2GB
=> Add Android screenshot if failed and test refactor

package/Editor.meta, package/README.md.meta, package/Runtime.meta, package/package.json.meta, scripts/pack.ps1
New pack script:
1. Copy `package-dev` but exclude aliasing, tests, asmdef,...
2. Copy missing .meta files and files we want to override from `package`
3. Copy Changelog, Licence and Samples
4. zip it - ship it
=> fix: Release packaging

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs
Fixes: https://github.com/getsentry/sentry-unity/issues/400 and can also be seen here: https://github.com/getsentry/sentry-unity/issues/432#issuecomment-982952428 by creating an additional import with `User/.../Unity/Builds/...`
- Copying files from the package under Windows requires the full path.
- The framework now gets added properly to the Xcode project. It relies on relative paths to work platform independently.
=> fix: Xcode Sentry.framework import

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs
With `bitcode` enabled and at the end of building for an archive, we upload all `symbols` and `bcsymbolmaps` we find in the output directory.
TODO: Needs documentation that the users either have to set up App Store Connect Integration or down- and upload the dSYMs themselves.
=> feat: iOS symbol upload with bitcode enabled

CHANGELOG.md, src/Sentry.Unity.Editor/SentryWindow.cs
Missed a dirty flag so changes to the sentry-cli options end up getting lost.
=> fix: Config windows saves changes to sentry-cli options

CHANGELOG.md, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs, test/Sentry.Unity.Editor.Tests/Android/AndroidManifestConfigurationTests.cs
With automatic symbols upload enabled and scripting backend not IL2CPP we currently break builds because we're looking for symbol files that don't exist.
That and we were missing a bunch of upload feature related tests.
=> fix: Symbol upload requires IL2CPP

.github/workflows/ci.yml
I might be misunderstanding the use-case for test results but right now: If the tests fail the upload gets skipped.
=> fix: CI uploading test results on failure

test/Sentry.Unity.Editor.Tests/SentryCliTests.cs
ScriptableObjects don't like to be created with `new`.
=> fix: ScriptableObject creation in SentryCliTests

.github/workflows/ci.yml
By default it only warns
Example: A build that was successful, now fails with:
=> fail ci if artifact is missing

.github/workflows/ci.yml, samples/unity-of-bugs/ProjectSettings/ProjectVersion.txt
=> chore: Bump CI and sample sample to 2019.4.33

CHANGELOG.md, samples/unity-of-bugs/Assets/Resources/Sentry/SentryOptions.asset, src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, src/Sentry.Unity.Editor/SentryCli.cs, test/Sentry.Unity.Editor.Tests/Sentry.Unity.Editor.Tests.csproj, test/Sentry.Unity.Editor.Tests/SentryCliTests.cs
Fixes: https://github.com/getsentry/sentry-unity/issues/456
Now there is a check in place to prevent us from trying to override an already existing sentry-cli executable.
=> fix: Added a file exists check for sentry-cli exec

CHANGELOG.md, Directory.Build.props
=> explicitly set <SignAssembly>false</SignAssembly>

.github/workflows/ci.yml, CHANGELOG.md, Directory.Build.props, Directory.Build.targets, src/Sentry.Unity/Protocol/Unity.cs, test/Directory.Build.props, test/Scripts.Tests/package-release.zip.snapshot, test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
NOTE: I had to push a branch to the .NET SDK since the addition of a .targets there broken the inheritance flow to this repo:
https://github.com/getsentry/sentry-dotnet/pull/1397
I suggest we move on with this to unblock the next release. And iterate from there
=> fix: bump submodules

test/Directory.Build.props
The `AfterTargets="FindUnity"` in the test build.props is too soon. `RestorePackages` and `CreatePackages` have to run first.
=> fix: Building clean repo

CHANGELOG.md, src/Sentry.Unity/UnityEventProcessor.cs, test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
=> Tag whether event was created in the UI thread

src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, test/Sentry.Unity.Editor.iOS.Tests/BuildPostProcessorTests.cs
Issues (e.g. https://github.com/getsentry/sentry-unity/issues/465) about successful Unity builds but missing Sentry.framework keep coming up.
If we failed to copy the framework to the target we throw and log the paths so at least we know what's going on.
=> fix: Added check for Sentry.framework copy success

CHANGELOG.md, src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs, test/Sentry.Unity.Editor.Tests/Android/DebugSymbolUploadTests.cs
Gradle requires paths containing backslashes to be escaped.
=> fix: Escaping sentry-cli path on Windows for gradle

.github/workflows/ci.yml
The Unity-Hub 3 `fails successfully` during the install process.
This seems to always have been the case on Windows and that's why we just ignore the return code on macOS now too.
=> CI: Using to setup-unity fork to ignore Unity Hub return code on macOS

.github/workflows/ci.yml, CHANGELOG.md, src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs, test/Sentry.Unity.Editor.Tests/Android/DebugSymbolUploadTests.cs
The previous PR #507 missed the symbols path. Also, for consistency in the `gradle.build`file I opted to replace Windows path backslashes with slashes (the hardcoded paths already use slashes)
=> Gradle: Replacing backslashes with slashes on Windows

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, samples/unity-of-bugs/Assets/Scripts/SmokeTester.cs, src/Sentry.Unity.Android/SentryNativeAndroid.cs, test/Sentry.Unity.Android.Tests/SentryNativeAndroidTests.cs
Aims to fix: https://github.com/getsentry/sentry-unity/issues/499
On Mono, when an actual crash happens and we reinitialized the native backend the app does what it's supposed to do when it crashes. It crashes. To prevent this we only reinizialize when building with IL2CPP.
=> fix: Reinitializing native backend for IL2CPP only

scripts/repack.ps1
When modifying the package contents there are quite a few manual steps required.
The result of running `./scripts/repack.ps1` is a new snapshot of the package to contain the added/removed files.
=> feat: Added a repackage script

CHANGELOG.md, samples/unity-of-bugs/Assets/Scripts/BugFarmButtons.cs, src/Sentry.Unity/UnityLogException.cs, test/Sentry.Unity.Tests/IntegrationTests.cs, test/Sentry.Unity.Tests/TestBehaviours/TestMonoBehaviour.cs, test/Sentry.Unity.Tests/UnityLogExceptionTests.cs
Resolving https://github.com/getsentry/sentry-unity/issues/532
=> feat: Marking Unity exceptions as unhandled by default

.github/workflows/ci.yml
this is the output of me doing `ctrl+s` in vs-code... merging this now would help avoid conflicts with other PRs, especially with the one where I'm splitting up the build job
=> chore: format ci.yml to avoid later conflicts on other PRs

.github/workflows/ci.yml, .github/workflows/sdk.yml, test/Scripts.Tests/android-libs.snapshot, test/Scripts.Tests/test-pack-contents.ps1
Fixes a regression introduced by #547 - native libs were not collected anymore
TODO: where are these libs used? Do we need them in the final artifact [as they were before](https://github.com/getsentry/sentry-unity/blob/e1ddb54972935499fbca95c1558916b941d7e0c2/.github/workflows/ci.yml#L286) or can we just have a separate artifact "Android-libraries" (or a similar name)
=> Regression: collect android native libraries as an artifact

CHANGELOG.md, package/Editor/iOS/Sentry.Unity.Editor.iOS.dll.meta, src/Sentry.Unity.Editor/SentryPreprocessBuild.cs
Closes: https://github.com/getsentry/sentry-unity/issues/525
Instead of requiring users to have the iOS module installed or embed the package and delete the `Sentry.Unity.Editor.iOS.dll` to get rid of the error, we set the default import settings to `OSX only`. 
If a user targets iOS on Windows we log the problem with a solution.
=> fix: Sentry.Unity.Editor.iOS is 'OSX only' by default

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/AdvancedTab.cs, src/Sentry.Unity.Editor/ScriptableSentryUnityOptionsEditor.cs, src/Sentry.Unity/ScriptableOptionsConfiguration.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, test/Sentry.Unity.Editor.Tests/ScriptableSentryUnityOptionsTests.cs, test/Sentry.Unity.Tests/ScriptableSentryUnityOptions.cs
The idea is to allow users to programmatically interact with the Sentry options i.e. interact with BeforeSend.
We provide the users with a snippet that lets them create a scriptable object. The path `Assets/Resources/Sentry/` is provided.
```
using Sentry.Unity;
using UnityEngine;
[CreateAssetMenu(fileName = "Assets/Resources/Sentry/OptionsConfiguration", menuName = "Sentry/OptionsConfiguration", order = 999)]
public class MyOptionsConfiguration : ScriptableOptionsConfiguration
{
public override void Configure(SentryUnityOptions options)
{
// Your code here
}
}
```
=> feat: Support for programmatic option configuration

CHANGELOG.md, samples/unity-of-bugs/Assets/Scripts/CustomOptionsConfiguration.cs, samples/unity-of-bugs/Assets/Scripts/CustomOptionsConfiguration.cs.meta, test/Scripts.Tests/package-release.zip.snapshot
Unfortunately, we ship our sample with just the scenes and scripts. So the user has to add an instance of the scriptable object to their own configuration window by hand.
=> feat: Added custom options configuration to samples

.github/workflows/ci.yml, Directory.Build.targets, samples/unity-of-bugs/Assets/Editor/Builder.cs, test/Scripts.Integration.Test/IntegrationGlobals.ps1, test/Scripts.Integration.Test/integration-build-project.ps1, test/Scripts.Integration.Test/integration-create-project.ps1, test/Scripts.Integration.Test/integration-run-smoke-test.ps1, test/Scripts.Integration.Test/integration-update-sentry.ps1
See #449 
Uses a linux+docker based Unity to prepare "build projects" for all platforms and then runs the actual build on the target platforms
=> Build in linux docker, test on supported platforms

CONTRIBUTING.md, Directory.Build.targets
I'm often cleaning the whole checkout (`git clean -ffxd; git submodule foreach --recursive git clean -ffxd`) to verify things locally and then copying the package-dev/Plugins from my local backup... this would allow anyone to get these from the latest successful job on the `main` branch
=> Enable developers to download native SDKs from GitHub artifacts

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/AdvancedTab.cs, src/Sentry.Unity.Editor/ConfigurationWindow/OptionsConfigurationTab.cs, src/Sentry.Unity.Editor/ConfigurationWindow/SentryWindow.cs
The goal is to have the least amount of steps between the config window and a user that just wants to write code.
The added `options config` tab allows the user to add the scriptable object that gets called during runtime initialization.
The button does:
1. Creates a script from a template at a user-selected location
2. Instantiates the scriptable object from the script and assigns it
Multiple button clicks allow for replacing of the script.
Already assigned scriptable objects do not get overwritten in the config window.
=> feat: Editor support for options configuration

.gitignore, CHANGELOG.md, package-dev/Plugins/iOS/SentryNativeBridge.m.meta, src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs, test/Sentry.Unity.Editor.iOS.Tests/BuildPostProcessorTests.cs, test/Sentry.Unity.Editor.iOS.Tests/SentryXcodeProjectTests.cs
Due to the `.meta` import settings for the `SentryNativeBridge.m` Unity copied it over to the generated Xcode project whether NativeSupport was enabled/available or not.
We now exclude it on any platform and copy it over during build post-processing.
Stops https://github.com/getsentry/sentry-unity/issues/588 from breaking.
=> fix: Explicitly copy SentryNativeBridge during build post process

README.md
Just a nit so folks don't try 2018 versions higher than 2018.1 and old versions of 2019
=> Bump minimun version on readme to 2019.4

CHANGELOG.md, Directory.Build.targets, samples/unity-of-bugs/Assets/Resources/Sentry/SentryOptions.asset, samples/unity-of-bugs/ProjectSettings/EditorBuildSettings.asset, samples/unity-of-bugs/ProjectSettings/ProjectSettings.asset, src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs, src/Sentry.Unity.Editor/SentryCli.cs, src/Sentry.Unity.Editor/SentryCliOptions.cs, src/Sentry.Unity.Native/SentryNativeBridge.cs, src/Sentry.Unity/SentryUnityOptionsExtensions.cs, test/Sentry.Unity.Editor.Tests/Android/AndroidManifestConfigurationTests.cs, test/Sentry.Unity.Tests/SentryUnityOptionsExtensionsTests.cs
Part of windows native support #527
=> Feat: windows symbol upload

src/Sentry.Unity.Editor/ConfigurationWindow/OptionsConfigurationTab.cs, src/Sentry.Unity.Editor/ScriptableSentryUnityOptionsEditor.cs
I've started looking into custom options and though I'm moving on to other issues, we could at least merge the editor refactorings. The idea is to add a new script-select for each supported platform.
Part of #609 
=> Refactor: editor for custom options

.github/workflows/ci.yml
turns out the recent change wasn't so good... we still don't get proper CI on 3rd-party PRs and now we also don't get CI on changes by the unity-update action. This should fix that and with the change of the license secret to allow 3rd-party branches, we could even use it to manually trigger a run on those branches (hopefully)
=> CI: support a manual run and run on all pushes

src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
Adding parentheses to symbol paths fixes an issue where some symbols wouldn't be picked up when the project had a whitespace in its name.
=> Added parentheses to symbol paths which are passed to sentry-cli

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity/SentryUnity.cs
=> Don't run sentry-dotnet with multiple app instances at the same time (desktop)

CHANGELOG.md, samples/unity-of-bugs/Assets/Editor/AndroidManifestUpdater.cs, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs, test/Sentry.Unity.Editor.Tests/Android/AndroidManifestConfigurationTests.cs
=> fix: AndroidManifest update should remove old items first

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/DebugSymbolsTab.cs, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs, src/Sentry.Unity.Editor/SentryCli.cs, src/Sentry.Unity.Editor/SentryCliOptions.cs, test/Sentry.Unity.Editor.Tests/SentryCliTests.cs
This is useful for self-hosted users, as well as for local testing ;-)
=> feat: Added override for Sentry CLI URL

CHANGELOG.md, src/Sentry.Unity/Integrations/UnityApplicationLoggingIntegration.cs, src/Sentry.Unity/UnityLogException.cs, test/Sentry.Unity.Tests/UnityEventExceptionProcessorTests.cs, test/Sentry.Unity.Tests/UnityLogExceptionTests.cs
This replaces the hardcoded logic to decide if the Frame is InApp or not by the one used by the main SDK.
One question was raising during the development of this PR
Should we add the code
`            System.Diagnostics.Debug.Fail("This UnityLogException constructor should not be used, please use the one that gives the SentryOption as an argument.");
`
On 
```
internal UnityLogException() : base()
{
LogString = "";
LogStackTrace = "";
}
private UnityLogException(string message) : base(message)
{
LogString = "";
LogStackTrace = "";
}
private UnityLogException(string message, Exception innerException) : base(message, innerException)
{
LogString = "";
LogStackTrace = "";
}
```
Since they are not intended to be use by us?
Close #575
=> Refactor InApp logic from Stack Traces

test/Sentry.Unity.Tests/IntegrationTests.cs
https://github.com/getsentry/sentry-unity/runs/6009888332?check_suite_focus=true
```
Expected: "False"
But was:  null
Test StackTrace: at Sentry.Unity.Tests.IntegrationTests+<BugFarmScene_DebugLog>d__14.MoveNext () [0x00140] in /sentry-unity/test/Sentry.Unity.Tests/IntegrationTests.cs:265
at UnityEngine.TestTools.TestEnumerator+<Execute>d__7.MoveNext () [0x0004e] in /sentry-unity/samples/unity-of-bugs/Library/PackageCache/com.unity.test-framework@1.1.29/UnityEngine.TestRunner/NUnitExtensions/Attributes/TestEnumerator.cs:46
```
=> chore: disable flaky tests

CHANGELOG.md
Resolves https://github.com/getsentry/sentry-unity/issues/690
=> fix: Bumped .NET SDK for IL2CPP Json workaround

src/Sentry.Unity.Editor/ConfigurationWindow/SentryWindow.cs
It appears to be unncessary to call the AssetDatabase.Import on the XML file as its only used when building the end binary. By removing this call to Import the asset, it hopefully address the infinite loop issue that occurs on a clean project when first loading SentryWindow.cs. However, I say hopefully as I cannot verify that this fix address the infinite loop import as I don't know how to build the managed dlls for the SentryWindow.cs.
=> Addressing Infinite Loop issue 

src/Sentry.Unity/ScriptableSentryUnityOptions.cs, src/Sentry.Unity/SentryUnity.cs, src/Sentry.Unity/SentryUnityOptions.cs, src/Sentry.Unity/SentryUnityOptionsExtensions.cs, test/Sentry.Unity.Tests/SentryUnityOptionsExtensionsTests.cs
Mirroring the .NET SDK by moving `TryAttachLogger` to options extension `SetupLogging`.
=> ref: SetupLogging as extension 

CHANGELOG.md, src/Sentry.Unity/SentryUnityOptionsExtensions.cs
Resolves https://github.com/getsentry/sentry-unity/issues/716
=> feat: Added `DisableUnityLoggingIntegration` to SentryUnityOptions

CHANGELOG.md, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs, src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs, src/Sentry.Unity/Integrations/IApplication.cs, test/Sentry.Unity.Editor.Tests/Android/AndroidManifestConfigurationTests.cs, test/Sentry.Unity.Editor.Tests/Android/DebugSymbolUploadTests.cs, test/Sentry.Unity.Editor.Tests/TestUnityLoggerInterceptor.cs, test/Sentry.Unity.Tests/Stubs/TestApplication.cs, test/SharedClasses/TestLogger.cs
Starting with 2021.2 the caching directory changed from `Temp` to `Library`.
Additionally, the gradle project persists across builds, so the "append symbol upload" functionality must be reentrant and removed in case the user opts out at a later point.
=> fix: Android debug symbols 

CHANGELOG.md, src/Sentry.Unity/SentryMonoBehaviour.cs, test/Sentry.Unity.Tests/UnityEventProcessorTests.cs
After adding the exception handling to SentryInitialization.cs, I've noticed it doesn't collect any of the usual context. This fixes that (and maybe a few other very early user-space error captures). The original behaviour was to run the main thread info collection asynchronously in a coroutine. Now, we collect it right away during init.
https://sentry.io/organizations/sentry-sdks/issues/3267829133/events/2651b13a859b4859860b3f44859ffacd/?project=5439417
https://sentry.io/organizations/sentry-sdks/issues/3267829133/events/e12e6634035b4eb0bdc3c4349a5d03e1/?project=5439417
=> fix: collect main thread data synchronously during init

CHANGELOG.md, package-dev/Plugins/iOS/SentryNativeBridge.m, package-dev/Plugins/macOS/SentryNativeBridge.m, package-dev/Runtime/SentryInitialization.cs, samples/unity-of-bugs/Assets/Scripts/SmokeTester.cs, scripts/smoke-test-webgl.py, scripts/unity-utils.ps1, src/Sentry.Unity.Android/SentryJava.cs, src/Sentry.Unity.Android/SentryNativeAndroid.cs, src/Sentry.Unity.Native/SentryNative.cs, src/Sentry.Unity.iOS/SentryCocoaBridgeProxy.cs, src/Sentry.Unity.iOS/SentryNative.cs, src/Sentry.Unity/Sentry.Unity.csproj, src/Sentry.Unity/SentryUnityOptions.cs, src/Sentry.Unity/UnityEventProcessor.cs, src/Sentry.Unity/WebGL/SentryWebGL.cs, test/Sentry.Unity.Tests/UnityEventProcessorTests.cs, test/Sentry.Unity.iOS.Tests/SentryNativeIosTests.cs
closes #606 
-  the ID seems to persist across tabs & browser sessions, likely a cookie or local storage based, so pretty useful and in line with other platforms
- opening in a different browser or a private tab gives a new ID, which is also OK
=> Feat: Automatic user IDs on native crashes & .NET events

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity/Default/UnknownPlatform.cs, src/Sentry.Unity/UnityWebRequestTransport.cs
Uses UnityWebRequestTransport by default on other than the officially supported platforms.
(hopefully) fixes #290
=> feat: use single-threaded web worker on unknown platforms

samples/unity-of-bugs/Assets/Scripts/SmokeTester.cs, scripts/smoke-test-ios.ps1
The problem was that we're logging the whole HTTP message that's being sent to Sentry - since this is coming through logs, it's added as a breadcrumb. There are two parts to this: 1. the message, being part of breadcrumbs, is then again part of every other captured event, thus growing the size exponentially; 2. the HTTP message also contains a large binary attachment (screenshot). 
The attachment previously wasn't logged due to Unity not stringifying it properly in `application.LogMessageReceived`, but [since we've started using `Debug.unityLogger.logHandler` instead](https://github.com/getsentry/sentry-unity/pull/731/files#diff-ee5e6340639abe48354fb3b1955c5593c52338c45145ef550d253bab26cf8a13), it also started to include the escaped binary data in the log, thus …
=> Fix flaky iOS tests

.github/workflows/ci.yml, scripts/smoke-test-droid.ps1
The goal is to move the additional changes from the latest android test into a separate PR and then move back to the latest version of Android.
Changes:
- Updated action to setup the Simulators (Actions Logs are more organized by groups)
- Fix issue where some simulators may fail due to out of storage errors.
- Retry to install the APK if ADB  failed to communicate with the Device.
- Add new logic to close Alerts (the old one does not work with the latest devices plus when an alert happens it's more readable than having to visualize an xml with the UI information)
- Added additional step to concatenate the variables used by the Simulator steps (removing the if conditions from the smoke test + smoke test retry)
- Added logic to retrieve the latest Android version.
=> Refactor droid steps

src/Sentry.Unity/SentryUnityOptions.cs
sometimes in developemnt the `application.PersistentDataPath` had a trailing space on Windows... causing test failures
=> fix: trim CacheDirectoryPath

test/Sentry.Unity.Tests/IntegrationTests.cs
Should fix [this](
https://github.com/getsentry/sentry-unity/runs/6796442971?check_suite_focus=true) - my assumption is that it's flaky because after yield, we can't be sure the setup function finishes before the test runs:
```
Test 1058: DebugLogException_IsMarkedUnhandled
Unhandled log message: '[Exception] Exception: a6dee71e-6a24-4455-b0a2-010b8624555b Test Event'. Use UnityEngine.TestTools.LogAssert.Expect
Test StackTrace: Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object) (at /sentry-unity/src/Sentry.Unity/Integrations/UnityLogHandlerIntegration.cs:47)
Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object) (at /sentry-unity/src/Sentry.Unity/Integrations/UnityLogHandlerIntegration.cs:47) …
```
=> test: fix tests flaking with "Unhandled log message"

CHANGELOG.md, src/Sentry.Unity/Integrations/AnrIntegration.cs, src/Sentry.Unity/SentryMonoBehaviour.cs, test/Sentry.Unity.Tests/AnrDetectionTests.cs
fixes #794 
(tested manually on Android & iOS simulator)
=> fix: don't report ANR while the app is in the background

Directory.Build.targets, test/Scripts.Tests/package-release.zip.snapshot
to avoid having to do this: https://github.com/getsentry/sentry-unity/pull/811/commits/afd1681ba2c64e820b58a26241e8153b7ee416e8
=> chore: remove version from the android .jar

.github/workflows/ci.yml, Directory.Build.targets, test/Directory.Build.props
Resolves https://github.com/getsentry/sentry-unity/issues/480
The idea is to fetch the `TestRunner.dlls` from the template cache that comes with the installation. That way we no longer need to create a whole new project just to fetch it from the `Library` and we save some time and licenses in CI.
=> feat: Remove temp project creation from build process

CHANGELOG.md, scripts/download-sentry-cli.ps1, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
=> chore: update CLI to v2.2.0

Directory.Build.targets, src/Sentry.Unity.Editor/ConfigurationWindow/OptionsConfigurationTab.cs, src/Sentry.Unity.Editor/ConfigurationWindow/SentryTestWindow.cs, src/Sentry.Unity.Editor/ConfigurationWindow/SentryWindow.cs, src/Sentry.Unity.Editor/ConfigurationWindow/Wizard.cs, src/Sentry.Unity.Editor/ConfigurationWindow/WizardApi.cs, src/Sentry.Unity.Editor/SentryPackageInfo.cs, test/Sentry.Unity.Editor.Tests/WizardTests.cs
The goal is to have an onboarding flow that will have the user hit Sentry, select an org and project, and will pre-populate the DSN and the Sentry CLI options for symbol upload.
---------------------
Edit @vaind: cleaned this up [_somewhat_](https://github.com/getsentry/sentry-unity/pull/780/files/69b1be294e3a108c45dc10ab08e74f308cdba9bd..0fb1956caa17c6a532e24e285dcecd7072e53c70), resolved TODOs and usability issues. 
Remaining TODO: tests 😱 
Basic workflow:
----------------
<details>
<summary>First draft does (outdated):</summary>
Opens the browser:
prepopulates orgs:
Then projects:
After selecting, the normal window shows up. With DSN, Org and Proj slug and Auth token.
</details>
=> feat: setup wizard

src/Sentry.Unity/ScriptableSentryUnityOptions.cs, src/Sentry.Unity/SentryUnityOptions.cs, src/Sentry.Unity/SentryUnityOptionsExtensions.cs
Checking the opt-in flag in the constructor does not work since it would have to be passed as an argument.
=> fix: Adding the IL2CPP processor outside the constructor

package-dev/Runtime/SentryInitialization.cs
Unity 2020 does not *return* a newly allocated string as out-parameter,
but rather expects a pre-allocated buffer it writes into.
=> fix: Avoid crashes on Unity 2020 when capturing native stack

package-dev/Plugins/macOS/SentryNativeBridge.m, src/Sentry.Unity.Editor.iOS/NativeOptions.cs, src/Sentry.Unity.iOS/SentryCocoaBridgeProxy.cs
closes #838 
#skip-changelog (no user visible change because the native cocoa SDK with the ANR enabled hasn't shipped yet)
=> chore: disable cocoa ANR detection

package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs
The `Sentry.Unity.Default` namespace no longer exists.
Added `#nullable` to get rid of build-time warnings: `The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.`
=> chore: Logging cleanup

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs
There is something off about the way we call native code on `x86` so I'm guarding the IL2CPP feature with `UNITY_64` for now:
```
error LNK2019: unresolved external symbol _il2cpp_gchandle_get_target@4 referenced in function _SentryUnityInfo_il2cpp_gchandle_get_target_m42BE043B96499DAF199C1045023BE6DE1B0FF6EA
Hint on symbols that are defined and could potentially match:
_il2cpp_gchandle_get_target
```
This can easily be reproduced with our own samples and `throw_cpp`.
=> fix: Added a x64 guard to the IL2CPP methods

.github/workflows/update-deps.yml
causes a lot of stress on CI which is an issue due to the limited number of Unity licences
=> chore: disable update-deps on PR merge

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs
The `UNITY_64` seems to block off the mobile platforms so I introduced a new definition based on our own `SENTRY_NAVIVE_*` definitions.
=> fix: Mobile IL2CPP line number support

test/Scripts.Integration.Test/create-project.ps1, test/Scripts.Integration.Test/update-sentry.ps1
The integration test build without sentry SDK (i.e. the first build) is currently disabled elsewhere than on the main branch because it "never" breaks. It broke in the recent split of integration test: #637 with error "Cannot build untitled scene.", as there was no scene in the app.
This PR moves the SmokeTester scene copy to an earlier point. It's OK to do this even though scripts (that are only copied later when the Sentry SDK is added) are bound to the scene - Unity just warns about the missing scripts but doesn't break the build.
=> Fix integration test on the main branch

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/AdvancedTab.cs, src/Sentry.Unity.Editor/ConfigurationWindow/CoreTab.cs, src/Sentry.Unity.Editor/ConfigurationWindow/DebugSymbolsTab.cs, src/Sentry.Unity.Editor/ConfigurationWindow/SentryWindow.cs
Added logging and icon highlights.
Highlight if the DSN is missing since it's the most crucial/fundamental part of the config:
Checking if the symbol upload is properly setup to set expectations:
In `Unity 2019`:
Symbol Upload Highlights for the required fields (best effort without actual validation of the input):
=> feat: Additional editor window utility

test/Sentry.Unity.Tests/SentryUnityTests.cs, test/Sentry.Unity.Tests/UnityEventScopeTests.cs, test/Sentry.Unity.Tests/UnityLogHandlerIntegrationTests.cs
closes https://github.com/getsentry/sentry-unity/issues/845
depends on https://github.com/getsentry/sentry-dotnet/pull/1743
=> test: async stacktrace

CHANGELOG.md, samples/unity-of-bugs/Assets/Resources/Sentry/SentryOptions.asset, samples/unity-of-bugs/ProjectSettings/ProjectSettings.asset, src/Sentry.Unity.Editor/ConfigurationWindow/TransportTab.cs, src/Sentry.Unity.Editor/ScriptableSentryUnityOptionsEditor.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, test/Sentry.Unity.Editor.Tests/ScriptableSentryUnityOptionsTests.cs, test/Sentry.Unity.Tests/ScriptableSentryUnityOptionsTests.cs
Due to being nullable `SampleRate` never actually got saved to the SentryOptions.asset. 
We pass it as `null` to the actual SentryUnityOptions to skip event drop checks in case it's `1.0f`.
=> fix: Save SampleRate to Options.asset

CHANGELOG.md, samples/unity-of-bugs/Assets/Scripts/NativeSupport/ObjectiveCPlugin.m, samples/unity-of-bugs/Assets/Scripts/NativeSupport/ObjectiveCPlugin.m.meta, test/Scripts.Tests/package-release.zip.snapshot
The `ObjectiveCPlugin.m` is missing from the samples.
=> fix: iOS native samples ObjectiveCPlugin

CHANGELOG.md, package-dev/Plugins/iOS/SentryNativeBridge.m
Resolves https://github.com/getsentry/sentry-unity/issues/866
=> fix: Made inline methods in Sentry Native Bridge static

samples/unity-of-bugs/Assets/Scripts/BugFarmButtons.cs
=> fix: Throwing new NullReference instead of 'null' in samples

CHANGELOG.md, src/Sentry.Unity/ScreenshotAttachment.cs
Resolves https://github.com/getsentry/sentry-unity/issues/925
With the .NET SDK filtering empty streams from being added to events, we can now return an empty `MemoryStream` instead of throwing an exception.
=> fix: Removed exception from screenshot attachment

.github/workflows/ci.yml
Excessively flaky.
Tracked by https://github.com/getsentry/sentry-unity/issues/946
=> ci: Excluded iOS 12.0 from CI

CHANGELOG.md, samples/unity-of-bugs/Assets/Resources/Sentry/SentryOptions.asset, src/Sentry.Unity.Editor/ConfigurationWindow/EnrichmentTab.cs, src/Sentry.Unity/ScreenshotAttachment.cs
Currently, the screenshot quality was relative to the current screen size which creates issues when a project supports a wide range of different resolutions, making "half the current resolution" on small screens barely usable.
Instead, we can map `High, Medium, Low` to "ranges" of resolutions akin to what Youtube videos offer.
```
ScreenshotQuality.Full => // Don't touch
ScreenshotQuality.High => 1920,     // 1080p
ScreenshotQuality.Medium => 1280,   // 720p
ScreenshotQuality.Low => 854,       // 480p
```
We take the wider side (portrait or landscape) and scale the screenshot to match while preserving the aspect ratio. (defacto @vaind's original implementation) with an user-facing enum instead of a `vec2 max resolution`.
=> fix: Screenshot quality

CHANGELOG.md, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs
Google Ads comes with its own `External Dependency Manager` that copies the `aar` into the project's plugin folder. This leads to issues during runtime.
Since we don't use the Android AppLifecycle (`session auto tracking`) feature we disable adding breadcrumbs by default.
```
FATAL EXCEPTION: main
Process: com.DefaultCompany.SentryIOAndroidCrash, PID: 736
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
at android.app.ActivityThread.installProvider(ActivityThread.java:7774)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:7286)
at …
```
=> fix: Google Ads dependency conflicts

CHANGELOG.md, src/Sentry.Unity.Android/SentryNativeAndroid.cs
Resolves https://github.com/getsentry/sentry-unity/issues/960
Failing to reinstall the backend (I've seen the events but failed to reproduce it myself) leads to the SDK capturing exceptions it creates itself.
=> fix: Capture failed reinstall backend gracefully

CHANGELOG.md, src/Sentry.Unity/ScriptableSentryUnityOptions.cs
fixes #968 
replaces & closes #970
=> fix: don't access Unity `AnalyticsSessionInfo.userId` on unknown platforms

CHANGELOG.md, src/Sentry.Unity.Editor/Il2CppOption.cs
=> fix: keep previously set IL2CPP compiler arguments

CHANGELOG.md, src/Sentry.Unity/ScreenshotAttachment.cs
Resolves https://github.com/getsentry/sentry-unity/issues/975
Releasing the resized temp render texture.
=> fix: Releasing temp render texture

CHANGELOG.md, src/Sentry.Unity.Editor/Il2CppBuildPreProcess.cs, src/Sentry.Unity.Editor/Il2CppOption.cs, test/Sentry.Unity.Editor.Tests/Il2CppBuildPreProcess.cs
The additional arguments get saved to disk at `<project>/ProjectSettings/ProjectSettings.asset`.
So we should manage adding and removing the argument.
=> fix: IL2CPP additional arguments

CHANGELOG.md, src/Sentry.Unity/ScreenshotAttachment.cs, src/Sentry.Unity/SystemInfoAdapter.cs, test/Sentry.Unity.Tests/UnityEventScopeTests.cs
replaces #1017 
fixes #935 
Tested manually on Unity 2021: mac (editor & player), iOS & Android; Unity 2019: Windows (editor & player), Linux
@bitsandfoxes can you check the device reported to be broken in the issue?
=> fix: screenshot orientation on some devices

.github/workflows/ci.yml, .github/workflows/format-code.yml, .github/workflows/release.yml, .github/workflows/sdk.yml, .github/workflows/update-deps.yml, scripts/smoke-test-droid.ps1
outstanding issue: `setup-unity` action needs to be updated to node16 & latest `@actions/core` - I've tried doing it quickly in [a fork](https://github.com/vaind/setup-unity/tree/chore/update-deps) but windows build didn't work so let's wait for the upstream maintainer to do it
=> ci: update deprecated actions

CHANGELOG.md, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs
Resolves https://github.com/getsentry/sentry-unity/issues/1037
Typo.
Might be worth considering adding a list of "packages that might/do create friction" to the smoketest?
=> fix: Disabled Android lifecycle breadcrumbs

NuGet.config
Especially in CI we've seen a lot of this lately.
```
Unable to resolve 'UnoptimizedAssemblyDetector (>= 0.1.1)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'Roslynator.Analyzers (>= 4.1.1)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'Nullable (>= 1.3.1)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'SIL.ReleaseTasks (>= 2.5.0)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'Microsoft.SourceLink.GitHub (>= 1.1.1)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'NETStandard.Library (>= 2.0.3)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'System.Reflection.Metadata (>= 5.0.0)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'System.Buffers (>= 4.5.1)' for '.NETStandard,Version=v2.0'.
Unable to resolve 'System.Threading.Tasks.Extensions (>= 4.5.4)' for …
```
=> fix: nuget building flake

src/Sentry.Unity/ScreenshotAttachment.cs, src/Sentry.Unity/SentryMonoBehaviour.cs, src/Sentry.Unity/SentryUnityOptions.cs, test/Directory.Build.props, test/Scripts.Integration.Test/common.ps1, test/Sentry.Unity.Tests/ScreenshotAttachmentContentTests.cs
Resolves https://github.com/getsentry/sentry-unity/issues/914
Note: We already discussed if we should not have an API to query the `IsMainThread` the SDK uses internally. Maybe this might be reused?
=> fix: Added missing screenshot tests

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs
This only came up when trying to distribute the app.
Adding the `.xcframework` also added it to the `Copy Bundle Resource` phase where it does not belong.
The change seems to be introduced with the switch to `xcframework` instead of a `framework`.
=> fix: Removing Sentry.framework from being copied as ResourceBundle

.github/workflows/ci.yml, scripts/smoke-test-droid.ps1, scripts/smoke-test-ios.ps1, scripts/smoke-test-webgl.py, test/Scripts.Integration.Test/Scripts/SmokeTester.cs, test/Scripts.Integration.Test/common.ps1, test/Scripts.Integration.Test/create-project.ps1, test/Scripts.Integration.Test/integration-test.ps1, test/Scripts.Integration.Test/run-smoke-test.ps1, test/Scripts.Integration.Test/symbol-upload-server.py
* closes #719 
* related also to #698 
* ensures HW acceleration is enabled for Android: see https://github.com/ReactiveCircus/android-emulator-runner/pull/279/files mentioning macos no longer comes with HAXM preinstalled
* some more CI log output improvements
* sets scripts `$ErrorActionPreference = "Stop"` & fixes the previously silent errors
* switches to x86_64 Android build
* ~records Android CI sessions~ - this slows down CI and doesn't actually show anything useful. below is the code for backup: [`61e6a34` (#1035)](https://github.com/getsentry/sentry-unity/pull/1035/commits/61e6a348ca509cccda05083099c34d63ecb5ec26)
```yaml
- name: Record test session
shell: bash
run: |
set -x
command -v ffmpeg || brew install ffmpeg
mkdir -p ${{ env.ARTIFACTS_PATH }}
ffmpeg -codecs
ffmpeg -nostdin …
```
=> ci: update OS versions in mobile test matrix & fix flaky tests

.github/workflows/ci.yml
It's all tested already when a release is launched. The integration tests are flaky no matter what we do... This regularly breaks releases. 
Assuming we don't run release when the main branch is not green, it shouldn't be necessary to run integration tests again on the release branch - thus we can make a release faster and without failing all the time.
=> ci: don't run all the integration tests on the release branch

.github/workflows/ci.yml, Directory.Build.props, Directory.Build.targets, scripts/ci-docker.sh, src/Directory.Build.props, test/Directory.Build.props
The context:
Building the SDK depends on the `TestRunner.dll` that comes with the Unity installation. Which version of Unity depends on the version that last [last opened the sample project](https://github.com/getsentry/sentry-unity/blob/b37e98159bf94cc165d2a0ddb23e41771b59bff2/Directory.Build.targets#L354) (locally, 2019 by default) or that has been set in the environment.
With the 2021 LTS and 2022 going forward, `TestRunner.dll` starts depending on netstandard2.1. This creates issues when trying to build the Tests.
The problem:
Setting the default target framework in the `PropertyGroup` and then overwriting it within a target seems to create some order of execution related issues. The overwritten version would be set to the variable but (somehow?) not get applied when actually …
=> chore: Updated `TargetFramework`handling

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, test/Scripts.Integration.Test/common.ps1, test/Scripts.Integration.Test/integration-test.ps1
Resolves https://github.com/getsentry/sentry-unity/issues/1071
- Forcing the symbol upload in the foreground to have the logs available in the Xcode console.
- Removing the log level from the command because we write it into the `.properties` already
- Removed `note:` because it was messing with the order of logs
=> fix: Symbol upload logging for iOS

CHANGELOG.md, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs, src/Sentry.Unity.Editor/Sentry.Unity.Editor.csproj, test/Scripts.Tests/package-release.zip.snapshot
Closes #1053
This can already be merged but will only start having an effect with https://github.com/getsentry/sentry-dotnet/pull/2050
* Unity 2019 - won't work - PDBs are not available - at least not the right ones, there are some but they don't match the final built app.
* [Windows Unity 2021](https://sentry.io/organizations/sentry-sdks/issues/3300403573/events/c6e25dc2530a45fc9d4a609a3a12c0b4/?project=5439417)
* [Linux Unity 2020](https://sentry.io/organizations/sentry-sdks/issues/3261854748/events/f28c26c23f59401da15a5f4112f5e460/?project=5439417)
* Android not working at the moment, see https://github.com/getsentry/sentry-dotnet/pull/2050#pullrequestreview-1208105473
* [MacOS Unity 2021](https://sentry.io/organizations/sentry-sdks/issues/3261854748/events/3fca11198f5a4584b0519cfbd93b2 …
=> feat: Mono PDB files upload during build

CHANGELOG.md, src/Sentry.Unity/ScriptableSentryUnityOptions.cs
We should not log a warning about not being able to find the IL2CPP methods when running in the Editor.
=> fix: Not adding the IL2CPP processor when in Editor

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs
Resolves https://github.com/getsentry/sentry-unity/issues/1123
If we let the marshalling take care of the string it'll try to free the allocated memory with the "wrong" free and not the IL2CPP one.
=> fix: IL2CPP line number crash

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/OptionsConfigurationTab.cs, test/Scripts.Integration.Test/common.ps1
The classes those option configs inherit from have the same name as the script that gets generated leading to compile time errors when they get created.
=> fix: Option config script name

.github/CODEOWNERS
The previous change to whitelist the interesting bits doesn't work and I'm still getting spammed. Let's remove completely.
Still feel free to request review manually, I just don't want all the spam coming from the automatic  subscription to all PRs
=> chore: remove @vaind from codeowners

test/Scripts.Integration.Test/Scripts/SmokeTester.cs
I came across a few odd timeouts in the Smoketester and after consulting @mattjohnsonpint we suspect possible deadlocks due to multi-locking to be the reason for those. 
=> fix: Smoketester timeouts

CHANGELOG.md, CONTRIBUTING.md, package-dev/Plugins/macOS/SentryNativeBridge.m
Aligned the `NS_X_OrNil` methods with the ones from the iOS bridge from [here](https://github.com/getsentry/sentry-unity/pull/932).
=> fix: macOS bridge - inlined helpers are static too

samples/unity-of-bugs/Assets/Resources/Sentry/SentryOptions.asset
The wizard returns only 50 projects per org, sorted by creation date. And since we're power users here and sentry-unity is kinda old the wizard doesn't work anymore.
New project - same name. 
And I fixed the missing reference that fell through the renaming PR.
=> chore: New Sentry project

CHANGELOG.md, src/Sentry.Unity/Integrations/UnityLogHandlerIntegration.cs, test/Sentry.Unity.Tests/UnityLogHandlerIntegrationTests.cs
Edge-case: If the SDK initializes with the same options object multiple times the integration starts forwarding the logs to itself.
=> fix: Prevent `LoggingIntegration` from registering multiple times

CHANGELOG.md, src/Sentry.Unity/Integrations/UnityLogHandlerIntegration.cs, src/Sentry.Unity/SentryUnity.cs, test/Sentry.Unity.Tests/SentryUnityTests.cs, test/Sentry.Unity.Tests/UnityEventScopeTests.cs, test/Sentry.Unity.Tests/UnityLogHandlerIntegrationTests.cs
Especially since the SDK is self-initializing it should log in case of multiple inits.
=> feat: Log multiple SDK inits

src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, test/Sentry.Unity.Editor.iOS.Tests/BuildPostProcessorTests.cs
Resolves https://github.com/getsentry/sentry-unity/issues/1176
=> fix: Add more logging to iOS `BuildPostProcess`

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/DebugSymbolsTab.cs
We didn't intend to put this on the editor window and it caused some confusion as to `what to put there`. Since it's a very specific edge case and it's accessible from the `BuildTimeOptionsConfig` I think it can be removed from the editor window.
=> fix: Removed `Overrride Sentry URL` from editor window

CHANGELOG.md, src/Sentry.Unity/SentryUnitySDK.cs
Closing the SDK results in a warning on non-windows player platforms. (especially prominent in the editor) because the lock was never set.
=> fix: lockfile check

samples/unity-of-bugs/Assets/Plugins/Sentry.meta
On the first opening of the sample, the meta without its directory creates a warning.
The cli options and the directory get created during the opening of the editor window.
=> chore: Removed unused meta in sample

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/OptionsConfigurationTab.cs, src/Sentry.Unity.Editor/ScriptableSentryUnityOptionsEditor.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, test/Sentry.Unity.Tests/ScriptableSentryUnityOptionsTests.cs
Already put breaking changes around the programmatic configuration.
Progress in the quest of being more explicit: `RuntimeOptionsConfig`
=> chore: Renamed `OptionsConfig` to `RuntimeOptionsConfig`

.gitignore
Follow-up of https://github.com/getsentry/sentry-unity/pull/1192
Don't track `meta` of ignored directory.
=> chore: Ignore `Plugins/Sentry.meta`

test/Sentry.Unity.Tests/UnityViewHierarchyAttachmentTests.cs
A mishap with having a dependency on the submodule and then bumping and merging it.
=> fix: UnityViewHierarchy tests

CHANGELOG.md, src/Sentry.Unity/Integrations/AnrIntegration.cs, test/Sentry.Unity.Tests/AnrDetectionTests.cs
Resolves https://github.com/getsentry/sentry-unity/issues/1214
=> fix: Make ANR detection unaffected by `Time.timescale`

CHANGELOG.md, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
Unity allows for the use of [Assembly Definitions](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) which leads to the creation of separate `.dll` and `.pdb` files. Currently, those get skipped due to the naming restriction.
=> fix: Uploading all `.pdb` at `Temp/ManagedSymbols` for Mono on Windows

.github/workflows/ci.yml, CHANGELOG.md, scripts/repack.ps1, test/Scripts.Tests/package-release.zip.snapshot
Resolves https://github.com/getsentry/sentry-unity/issues/1245
=> fix: Aliasing `Microsoft` Editor dependencies

samples/unity-of-bugs/Assets/Scripts/RuntimeConfiguration.cs
This would break initialization in the sample.
=> fix: During `runtimeinit` the scene does not yet exist

CHANGELOG.md
=> fix: Revert `Java SDK` bump to `6.14.0`

Directory.Build.props
From testing this locally it worked fine until I tried building with 2022.
```
error CS1705: Assembly 'UnityEngine' with identity 'UnityEngine, uses 'netstandard, Version=2.1.0.0", 
which has a higher version than referenced assembly 'netstandard' 
with identity 'netstandard, Version=2.0.0.0' [/Users/bitfox/Workspace/sentry-unity/src/Sentry.Unity/Sentry.Unity.csproj]
```
=> chore: Added override to build locally with 2022

.github/workflows/ci.yml
Renaming the steps to put the versions first because this view is driving me nuts.
=> chore: Renaming CI steps to lead with version numbers

.github/workflows/ci.yml
=> chore: Dropping iOS `12.4` and `14.5` tests in CI

CHANGELOG.md, src/Sentry.Unity/Integrations/UnityLogHandlerIntegration.cs, test/Sentry.Unity.Tests/UnityLogHandlerIntegrationTests.cs
Resolves https://github.com/getsentry/sentry-unity/issues/1262
=> fix: CaptureLogFormat throws when `args` contain `null`

.github/workflows/ci.yml
Someone is lying here.
Based on :https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md there should be `15.5` for macOS-12. But based on CI there isn't.
=> chore: Downgrading iOS version

CHANGELOG.md, src/Sentry.Unity.Editor/AutoInstrumentation/SentryPerformanceAutoInstrumentation.cs
The SDK no longer instruments performance with the SDK disabled.
=> fix: Don't run instrumentation with the SDK disabled

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/NativeOptions.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, src/Sentry.Unity/SentryUnityOptions.cs, test/Sentry.Unity.Editor.iOS.Tests/NativeOptionsTests.cs
We had filtering of `BadGatewayExceptions` on the C# layer. If enabled, these need to be propagated down to the native layer as well.
=> feat: Filter Unity telemetry `BadGatewayException` on iOS native layer

CHANGELOG.md, src/Sentry.Unity.Editor/Android/GradleSetup.cs, test/Sentry.Unity.Editor.Tests/Android/GradleSetupTests.cs, test/Sentry.Unity.Editor.Tests/TestFiles/SymbolsUploadProject/GradleProject/settings.gradle
Resolves https://github.com/getsentry/sentry-unity/issues/1355
With `2022.3.0f1` and forward the base gradle template has been updated. The SDK needs to add the local repository to the `settings.gradle` instead of the `build.gradle`.
=> fix: Fixed `Failed to find repositories` on `2022.3.0f1` builds

CHANGELOG.md, src/Sentry.Unity/Il2CppEventProcessor.cs, test/Sentry.Unity.Tests/UnityIl2CppEventExceptionProcessorTests.cs
Trimming `0` on UUIDs with a trailing `0` leads to a malformed UUID and failure to symbolicate.
=> fix: Image UUID normalization

scripts/smoke-test-webgl.py
The automatic bump to Selenium 4.10 leads to:
```
Traceback (most recent call last):
File "/home/runner/work/sentry-unity/sentry-unity/scripts/smoke-test-webgl.py", line 180, in <module>
driver = TestDriver()
File "/home/runner/work/sentry-unity/sentry-unity/scripts/smoke-test-webgl.py", line 150, in __init__
self.driver = webdriver.Chrome(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'desired_capabilities'
```
Can be seen [here](https://github.com/getsentry/sentry-unity/actions/runs/5250781239/jobs/9485479485).
Trying to follow the [upgrade-docs](https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#capabilities)
=> fix: CI selenium update

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs
It's been deprecated and removed from all kinds of places.
=> feat: Remove bitcode check from iOS builds

src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs
Continuation of https://github.com/getsentry/sentry-unity/pull/1381/files
I read the check wrong. We actually want to upload `always` now.
=> feat: Always upload debug symbols on iOS

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity/ISentryUnityInfo.cs, src/Sentry.Unity/Il2CppEventProcessor.cs
Resolves https://github.com/getsentry/sentry-unity/issues/1442
=> fix: IL2CPP in Unity 2023

.github/workflows/ci.yml
Looks like the runners are running out of disk space when building the smoketest for Android.
=> chore: Free some disk space in CI

src/Sentry.Unity/Integrations/SceneManagerIntegration.cs, src/Sentry.Unity/Integrations/UnityBeforeSceneLoadIntegration.cs, test/Sentry.Unity.Tests/SceneManagerIntegrationTests.cs
Integration registration already DebugLogs `Registering integration: '{0}'.`
=> ref: Removed redundant integration registry logs

CHANGELOG.md, src/Sentry.Unity/SentryMonoBehaviour.cs, test/Sentry.Unity.Tests/SentryMonoBehaviourTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1458
Am I missing something? Why did we need to special-case it? Worst case we're pausing twice but `UpdatePauseStatus` is reentrant and handles that anyway.
=> fix: Made SDK pause event agnostic

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/NativeOptions.cs
Fixed the setting of `attachScreenshot` on the native options.
=> fix: Attaching screenshots on native iOS crashes

src/Sentry.Unity.Editor.iOS/NativeOptions.cs
Setting the SKD name has to happen through `PrivateSentrySDKOnly`. The SDK name no longer gets picked up through the options.
=> fix: SDK name reporting on iOS

samples/unity-of-bugs/Assets/Scripts/Editor.meta, test/Scripts.Integration.Test/Editor/Builder.cs
For whatever reason we're suddenly stuck with `.gz` on WebGL builds but on 2021 only?
=> fix: WegGL smoketest

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity/ISentryUnityInfo.cs, src/Sentry.Unity/Il2CppEventProcessor.cs, src/Sentry.Unity/SentryUnityOptionsExtensions.cs, test/SharedClasses/TestUnityInfo.cs
Fixed the checks for `RuntimePlatform` in the IL2CPP exception processor. Those need to be conditionally compiled with the game.
=> fix: IL2CPP line number processing for dedicated server builds

test/Sentry.Unity.Tests/IntegrationTests.cs, test/Sentry.Unity.Tests/TestBehaviours/TestMonoBehaviour.cs
We keep running into flaky tests in combination with `DebugLogException` and
```
Test 1064: DebugLogException_***
Unhandled log message: '[Exception] Exception: f39f46e8-d13a-445b-b25b-4ce562514c67 Test Event'.
```
I suspect the `LogAssert` is not working properly when logging within a `Task.Run`.
=> fix: Test fake

CHANGELOG.md, src/Sentry.Unity/SentryMonoBehaviour.cs
We continuously have issues regarding false positive ANR events coming in combination with Ad-SDKs from providers like AppLovin and Ironsource. These SDKs put the game in the background and or pause them. This seems to circumvent our `SentryMonoBehavious` hooks for pause/focus events.
Making the `UpdatePauseStatus` public allows users to manually unblock themselves by setting the SDK's pause status.
=> feat: Allow for manual application pause update

.github/workflows/ci.yml
GH images for all OSes updated Powershell to 7.4: https://github.com/actions/runner-images/issues/9115
The action `free-disk-space` removes `powershell` as part of [`large-packages`](https://github.com/jlumbroso/free-disk-space/blob/54081f138730dfa15788a46383842cd2f914a1be/action.yml#L181). What I don't get is why it was working before and why it's not working anymore.
Leaving `large-packages` changes from:
- Previously: 11 GB saved
- Now: 4 GB saved
which is still enough space. And we save 2 minutes.
=> fix: CI `pwsh: Command not found.`

src/Sentry.Unity/Integrations/UnityLogHandlerIntegration.cs
With session tracking disabled the SDK would log a warning on quit:
```
Sentry: (Warning) Attempted to pause a session, but a session has not been started. 
```
=> fix: Fixed session pause on quit

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs
The linking phase is still added multiple times, but I could not find a way to check if it is already added.
But this does not break the build.
=> fix: remove ios embed framework build phase duplication (#1558)

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity.Native/SentryNative.cs, src/Sentry.Unity.Native/SentryNativeBridge.cs
I'm not sure (yet) when that happened but Unity is overwriting the signal handler in newer versions. This prevents `sentry-native` from capturing native crashes. 
We have a similar situation on Android where we reinstall the backend to take back control so I'm taking the same approach to resolve this.
An open TODO: We have checks in CI specifically to make sure that does not break. Why does CI pass?
=> fix: Reinstall native backend 

src/Sentry.Unity/ScreenshotAttachment.cs
Relevant for 2021 and 2022 LTS.
On macOS CI, Unity doesn't accept RenderTextures with size 0 anymore. But because there is no screen in CI, width and height are 0.
```
Sentry: (Error) Failed to add attachment: screenshot.jpg. System.ArgumentException: RenderTextureDesc width must be greater than zero.
```
=> fix: Screenshot smoketest

.github/workflows/android-smoke-test-wrapper.yml, .github/workflows/ci.yml, test/Scripts.Integration.Test/Editor/Builder.cs
~~Looks like we never updated the Desktop runs to use Unity in the docker container.~~
So the reason is: Game CI does not provide docker container for macOS.
We're forking [github.com/kuler90/setup-unity](https://github.com/kuler90/setup-unity) to smoke test the package installation and editor setup the editor on Windows and macOS (because Game CI does not provide docker container for macOS). The GH action was "broken" since the version of the hub that is getting used is now aware of `intel` vs `silicone`.
Initially, I tried making it work opting into silicone where possible but hit some blockers with the progressive lightmapper. It requires a GPU, finds none in CI (duh), falls back to the CPU mapper but that's not supported on silicone. So, `intel` all the way it is!
=> fix: CI for Desktop

.gitignore, CHANGELOG.md, package-dev/Plugins/iOS/SentryCxaThrowHook.cpp, package-dev/Plugins/iOS/SentryCxaThrowHook.cpp.meta, samples/unity-of-bugs/Assets/Scripts/NativeSupport/CppPlugin.cpp, src/Sentry.Unity.Android/SentryNativeAndroid.cs, test/Scripts.Tests/package-release.zip.snapshot
Fixes #1628 
There are still some cases that are not covered by this fix.
If the exception is thrown not from UnityFramework, but from another library, the hook will not be called.
The details can be found in the conversation of the issue.
=> Improve C++ exceptions stacktrace on iOS

src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs, src/Sentry.Unity.Editor/Android/AndroidUtils.cs, src/Sentry.Unity.Editor/Android/PostBuildCheck.cs
The logs will be passed as warnings if the IgnoreCliErrors flag is set in the settings, and will be logged as info if the task was successful.
=> Pass CLI logs to Unity in any case for Android build

CHANGELOG.md, src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs, test/Sentry.Unity.Editor.Tests/Android/DebugSymbolUploadTests.cs
Fixes #1673 
Previously, we were binding to the assemble tasks that get executed during Unity build (regardless of whether it is apk or abb).
But for the exported projects .aab artifacts are only created using the bundle task, during which the upload symbol task was not executed.
=> Hook to bundle tasks during Android export for symbols upload

CHANGELOG.md, src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs, test/Sentry.Unity.Editor.Tests/Android/DebugSymbolUploadTests.cs
=> Fix symbol upload during .aab build from Unity

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/NativeOptions.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1658
It seems like there is some incompatibility with UnityWebReqest and the swizzling the Cocoa SDK is doing for it's network breadcrumb integration. Disabling this for now to stop breaking webrequests.
=> fix: WebRequests breaking on iOS

CHANGELOG.md, src/Sentry.Unity.Native/SentryNative.cs
Related to: https://github.com/getsentry/sentry-unity/issues/1440
We're not building the native SDK statically, but we can at least stop the exceptions from being thrown.
=> fix: Log native init failure instead of throwing

CHANGELOG.md, src/Sentry.Unity/Il2CppEventProcessor.cs
The IL2CPP exception processor relies on some sentry-native functionality to read from debug images. On i.e. Android, with Android native support disabled, sentry-native is not present, causing a DLL not found exception, breaking the processor.
=> fix: IL2CPP Exception processor now checks for native support being enabled

CHANGELOG.md, src/Sentry.Unity/ScriptableSentryUnityOptions.cs
Tracing requires file access which is not permitted on i.e. Nintendo Switch.
=> fix: Disable tracing on unknown platforms

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs
This PR fixes #1442 for Unity 6
=> fix: IL2CPP in Unity 6

CHANGELOG.md
=> fix changelog deps block

.github/workflows/ci.yml, CHANGELOG.md
This PR fixes the issue with loading `libsentry.so` on older Linux versions during Sentry initialization.
Switching to using Ubuntu 20.04 for building `sentry-native` in CI allows to preserve its compatibility with `GLIBC` libs that are available on older Linux versions.
Closes #1730 , #1719
=> fix: System.DllNotFoundException during Sentry initialization in Unity Headless Linux Server build

CHANGELOG.md, src/Sentry.Unity/SentryMonoBehaviour.cs
This PR adds `DontDestroyOnLoad` call to `SentryMonoBehavior.Awake` to ensure its instance won't be destroyed during the scene switch in WebGL builds.
Closes #1678
=> Fix `SentryMonoBehavior` instance being removed on scene switch in WebGL

.github/workflows/android-smoke-test.yml, .github/workflows/ci.yml, .github/workflows/sdk.yml
Committed via https://github.com/asottile/all-repos
=> deps: update actions/upload-artifact to v4

.github/workflows/ci.yml
We're installing Unity via `getsentry/setup-unity`. It's basically a wrapper around the Unity hub.
For some reason, the Unity installation for macOS changed with 2022 leading to 
```
Could not find Unity Package Manager local server application at [/Applications/Unity/Hub/Editor/{{insert-unity-version}}/Unity.app/Contents/Resources/PackageManager/Server/UnityPackageManager]
```
which itself seems to be regression of https://discussions.unity.com/t/could-not-find-upm-executable-at-path/809716/5 going back to the 2019 version. Also see see https://discussions.unity.com/t/failed-to-start-the-unity-package-manager/930285/14
Game CI now also provides Windows docker images. So that might be the way to move forward as well.
=> chore: Disable `macOS` smoke test in CI

CHANGELOG.md, src/Sentry.Unity/Integrations/AnrIntegration.cs, src/Sentry.Unity/Integrations/ApplicationNotRespondingException.cs, test/Sentry.Unity.Tests/AnrDetectionTests.cs
The `ApplicationNotResponding` exception was previously `internal`.
This can now be consumed i.e. in a `BeforeSend` callback to modify or filter
```
options.SetBeforeSend((sentryEvent, _) =>
{
if (sentryEvent.Exception is ApplicationNotRespondingException)
{
return null;
}
return sentryEvent;
});
```
=> feat: Added `ApplicationNotRespondingException` type

CHANGELOG.md, src/Sentry.Unity/Integrations/UnityScopeIntegration.cs, src/Sentry.Unity/MainThreadData.cs, src/Sentry.Unity/ScreenshotAttachment.cs, src/Sentry.Unity/SentryMonoBehaviour.cs, src/Sentry.Unity/SentryUnityOptions.cs, src/Sentry.Unity/SentryUnitySDK.cs, src/Sentry.Unity/UnityEventProcessor.cs, src/Sentry.Unity/UnityViewHierarchyAttachmentContent.cs, test/Sentry.Unity.Tests/ContextWriterTests.cs, test/Sentry.Unity.Tests/ScreenshotAttachmentContentTests.cs, test/Sentry.Unity.Tests/UnityEventScopeTests.cs, test/Sentry.Unity.Tests/UnityViewHierarchyAttachmentTests.cs
Initially, we deferred the collection of `MainThreadData` into our MonoBehaviour's Awake call. Since that data does not change at runtime, fetching it doesn't impose any performance impact (we were just doing it at a later point) we can rely on the `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]` attribute. That way we have the data available right after initialization and irrespective whether an error gets captured on the main/UI or a background thread.
=> feat: Collect `MainThreadData` before initial scene load

CHANGELOG.md, src/Sentry.Unity.Android/SentryJava.cs
Starting with `sentry-java` 6.7.1, `"vendorId"` is expected to be a String: https://github.com/getsentry/sentry-java/blob/6c8acb80b8a3a1991a7f614347c12c460a90c746/sentry/src/main/java/io/sentry/protocol/Gpu.java#L82
Not sure if we have ways to write tests for this, if so please let me know!
Related issue: https://github.com/getsentry/team-mobile/issues/67
=> fix: vendorId is a String in sentry-java

CHANGELOG.md, scripts/build-and-alias.ps1, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, test/Scripts.Integration.Test/Editor/Builder.cs, test/Sentry.Unity.Tests/ScriptableSentryUnityOptionsTests.cs, test/Sentry.Unity.Tests/UnityBadGatewayExceptionFilterTests.cs, test/Sentry.Unity.Tests/UnitySocketExceptionFilterTests.cs, test/Sentry.Unity.Tests/UnityWebExceptionFilterTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1804, https://github.com/getsentry/sentry-unity/issues/1779
Also reverts https://github.com/getsentry/sentry-unity/pull/1728
Tracing itself has nothing to do with file-write. Turns out that simply making the request requires some access to the file system 
https://github.com/getsentry/sentry-dotnet/blob/12c7d7ca046ab985b0267f43c5fd35f2caad108c/src/Sentry/Internal/Http/HttpTransport.cs#L42
=> fix: Disable file-write on unknown platforms

CHANGELOG.md, scripts/build-and-alias.ps1, src/Sentry.Unity/SentryUnityOptions.cs
This PR should prevent users from accidentally enabling `Enhanced` stack trace mode via the `SentryUnityOptions` parent class property. Enhanced mode is not supported in IL2CPP builds (see #1033 for more details) and thus could cause crashes like in #1783.
Closes #1783
=> Change access modifier to `private` for stack trace mode option setter

.github/workflows/ci.yml, test/Scripts.Integration.Test/Editor/Builder.cs
The issue is having to set `buildPlayerOptions.options = BuildOptions.AcceptExternalModificationsToPlayer;` only when exporting a Gradle project. Otherwise this breaks `main` in the `Build without SDK` step.
=> fix: main CI

.github/workflows/ci.yml, src/Sentry.Unity.Editor/Android/DebugSymbolUpload.cs
With the incremental builds, the added build-times for building an empty project are negligible. And it takes away a tiny bit of complexity.
=> fix: main CI for Unity 6 targeting Android

CHANGELOG.md, src/Sentry.Unity/MainThreadData.cs, src/Sentry.Unity/SentryUnitySDK.cs, test/Scripts.Integration.Test/Scripts/SmokeTester.cs, test/Scripts.Integration.Test/run-smoke-test.ps1, test/Sentry.Unity.Tests/ContextWriterTests.cs, test/Sentry.Unity.Tests/UnityEventScopeTests.cs
We moved the collection of `MainThreadData` out of the `MonoBehaviour`'s Awake call in https://github.com/getsentry/sentry-unity/pull/1802
I'm actually not 100% why that worked in the first place. The Awake happens past the SceneLoad so the contexts should not have been available at that time either.
- The SDK initializes during `RuntimeInitializeLoadType.SubsystemRegistration`
https://github.com/getsentry/sentry-unity/blob/03af53dcd6462bc2525e8abfcbef7f4ad8060c8e/package-dev/Runtime/SentryInitialization.cs#L54
- The SDK registers the integrations on the options
- The UnityScopeIntegration gets registered and populates the contexts
https://github.com/getsentry/sentry-unity/blob/e7a45a96ab82e20394c6ad8711e3e0011594798c/src/Sentry.Unity/Integrations/UnityScopeIntegration.cs#L46-L58
- The …
=> fix: Missing contexts

.github/workflows/ci.yml, package-dev/Tests/Editor/Sentry.Unity.Editor.iOS.Tests.dll.meta
Fixes https://github.com/getsentry/sentry-unity/issues/1272
Outputting the testresults confirms that the iOS tests now run as well.
=> chore: Run iOS tests on Ubuntu

src/Sentry.Unity.Editor/ConfigurationWindow/AdvancedTab.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1840
The error-box now lists the requirements and links to the docs, explaining how our IL2CPP line number support works.
=> fix: Improve IL2CPP debug symbol guidance in Editor

test/Sentry.Unity.Tests/IntegrationTests.cs, test/SharedClasses/TestEnvironment.cs
`DebugLogException_InTask_IsCapturedAndIsMainThreadIsFalse` is notoriously flaky in CI.
=> chore: Disable flaky test

CHANGELOG.md, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, test/Sentry.Unity.Tests/ScriptableSentryUnityOptionsTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1861
Calling `application.PersistentDataPath` implicitly creates a directory. So the SDK **must not** call into this Unity API if we're not sure if it's safe (known) to do so.
=> fix: Respect fileIO restrictions on unknown platforms

CHANGELOG.md, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs, test/Sentry.Unity.Editor.Tests/Android/AndroidManifestConfigurationTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1871
=> fix: Write `SampleRate` as `float` to manifest

.github/workflows/sdk.yml, CHANGELOG.md, Directory.Build.targets, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs, test/Scripts.Tests/package-release.zip.snapshot
Fixes https://github.com/getsentry/sentry-unity/issues/1866
We're currently very explicit with what we copy over from the `sentry-native` build
https://github.com/getsentry/sentry-unity/blob/4df953801eaf87d6de850c9756942dbf51637c4f/Directory.Build.targets#L212-L220
We need to include the `wer handler` as well.
=> fix: Add missing `WER handler` on Windows

.github/workflows/update-deps.yml
The original code relied on parsing a releases web page, which became flaky now that it is dynamic (loads actual release data after load has completed). I've found out there's an API so I'm using that instead. See https://services.docs.unity.com/release/v1/
also, I've updated the action dependency because the CI complains about node depreciation
=> CI: use REST API in the unity updater

Directory.Build.targets
Updated (copied from .NET SDK) the regex used to parse the current Cocoa SDK version.
See https://github.com/getsentry/sentry-dotnet/pull/3727#discussion_r1830302013 for more context.
=> fix: Cocoa version regex

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity.Android/SentryNativeAndroid.cs, src/Sentry.Unity.iOS/SentryNativeCocoa.cs
Relates to: https://github.com/getsentry/sentry-unity/issues/1727
When having the game run as a library, closing the game closes the SDK. This causes the surrounding app's native SDK to close as well.
Because the SDK can't determine the setup it is used in, it should only close the native SDKs if it is sure it was the one enabling it.
=> fix: Only close the native SDKs if native support has been enabled

CHANGELOG.md, package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity.Native/SentryNative.cs
The SDK will no longer attempt to reinstall the backend without native support enabled and without successful initialization.
It'll also capture `EntryPointNotFoundException` during reinstallation.
=> fix: Suppress and log known exceptions during native initialization

src/Sentry.Unity.Native/SentryNative.cs
=> fix: Logging

src/Sentry.Unity.Native/SentryNative.cs
Reverts https://github.com/getsentry/sentry-unity/pull/1900
I had https://github.com/getsentry/sentry-dotnet/pull/2715 and https://github.com/getsentry/sentry-dotnet/pull/3630 wrong in my head and assumed the order was the issue.
=> fix: Logger argument order

package-dev/Runtime/SentryInitialization.cs
Fixing the order of arguments when logging errors that provide exceptions introduced in
- https://github.com/getsentry/sentry-unity/pull/1898
- https://github.com/getsentry/sentry-unity/pull/1900
The [signature](https://github.com/getsentry/sentry-dotnet/blob/cbe1af4c722b22eb6ee0cbe5c70b25a8d7056d41/src/Sentry/Extensibility/DiagnosticLoggerExtensions.cs#L267C1-L270C24) is 
```
public static void LogError(
this IDiagnosticLogger logger,
Exception exception,
string message)
```
=> fix: Log error with exception argument order

samples/unity-of-bugs/Assets/Resources/Sentry/SentryOptions.asset, scripts/create-sentry-cli-options.ps1, src/Sentry.Unity.Editor/SentryCliOptionsEditor.cs
We've introduces programmatic configuration of the sentry CLI via dedicated scriptable object in https://github.com/getsentry/sentry-unity/pull/1887
I've updated the sample and the cli config that gets generated during repo restoration to properly connect those. We have to do it like that because the CLI options are explicitly not under version control. (i.e. auth token being sensitive)
=> chore: Updated sample

CHANGELOG.md, src/Sentry.Unity/UnityViewHierarchyAttachmentContent.cs
Resolves: https://github.com/getsentry/sentry-unity/issues/1918
Skips possible `null` components before trying to get their type info.
Not sure how to test this because it depends on a Unity API `GetComponents`
Also: replaced the LINQ call with a foreach and allocated a new List with the known size to avoid resizes.
=> fix: null ref in view hierarchy

scripts/repack.ps1
This is for local development only.
Pick the newest installed, it's just so much faster.
=> chore: Pick newest installed Unity for local repackaging

CHANGELOG.md, src/Sentry.Unity.Android/JniExecutor.cs, src/Sentry.Unity.Android/SentryJava.cs, src/Sentry.Unity.Android/SentryNativeAndroid.cs
Previously, if something went wrong while we were calling into Java, the game would freeze. Now we have a timeout of 1 frame to at least not break things.
=> fix: improve jni stability

.github/workflows/ci.yml, scripts/ci-setup-java.ps1
The default Java version is different on different runner images. An update to `-latest` causes Unity 2019 builds to fail.
With this, we explicitly set the correct Java version depending on the targeted Unity version, making this more resilient to future changes.
I've also added timeouts to the smoketests themselves. They tend to either fail fast or run indefinitely. This gets rid of the latter.
=> fix: CI - Set correct Java version

package-dev/Plugins/iOS/SentryNativeBridge.m
Fixes an issue reported in https://github.com/getsentry/sentry-unity/issues/1951#issuecomment-2581075951
The original code that starts the iOS native bridge caused
compile error by XCode due to the retaining excessive ownership which can lead to a memory leak.
error name during the compilation: 
"PerformSelector names a selector which retains the object".
this fix with PR was already been created by @bitsandfoxes 
but thanks to him I could create my own PR for the first time.
I really appreciate the community.
=> fix: iOS native bridge creation with parameters

CHANGELOG.md, src/Sentry.Unity/Integrations/AnrIntegration.cs, test/Sentry.Unity.Tests/AnrDetectionTests.cs
Addresses the improvement part of https://github.com/getsentry/sentry-unity/issues/1954
In line with Java and the [V1 ANR watchdog](https://github.com/getsentry/sentry-java/blob/bfbaf37fae93cd88c3c1cd570f6296af1bf064be/sentry-android-core/src/main/java/io/sentry/android/core/AnrIntegration.java#L144) (documented [here](https://arc.net/l/quote/zzpsagea)), the SDK will now add the `ANR` mechanism when capturing an ANR event.
Relates to:
* https://github.com/getsentry/sentry-unity/issues/1961
=> feat: Add mechanism to ANR event

CHANGELOG.md, package-dev/Plugins/iOS/SentryNativeBridge.m, package-dev/Plugins/iOS/SentryNativeBridgeNoOp.m, src/Sentry.Unity.iOS/SentryCocoaBridgeProxy.cs
A followup of https://github.com/getsentry/sentry-unity/pull/1964
=> fix: iOS native bridge import missing

samples/unity-of-bugs/Assets/Scripts/SentryOptionConfiguration.cs, src/Sentry.Unity/SentryOptionsConfiguration.cs
Cleanup of both, the template and the one in our `/Samples`.
=> chore: Cleanup OptionsConfiguration template

CHANGELOG.md, package-dev/Runtime/io.sentry.unity.dev.runtime.asmdef
Fixes https://github.com/getsentry/sentry-unity/issues/1962
=> fix: The `asmdef` no explicitly sets the included platforms

test/Scripts.Integration.Test/run-smoke-test.ps1
Similarly to the Android SmokeTests, where relying on Unity's exit code turned out to be flaky, we're checking the logs for the shutdown-marker `SmokeTester is quitting.` https://github.com/getsentry/sentry-unity/blob/037bcddbb0d56c93e76d1974c460c82f6133baf5/scripts/smoke-test-android.ps1#L336
=> chore: CI desktop flake

LICENSE.md
While updating the date ranges for multiple PRs, Michi pointed out that we don't need date ranges for our licenses. I'm sorry about the fuzz.
In our internal [Open Source Legal Policy](https://www.notion.so/sentry/Open-Source-Legal-Policy-ac4885d265cb4d7898a01c060b061e42), we decided that licenses don't require a data range. This also has the advantage of not updating the date range yearly.
cc @gavin-zee
=> Remove date range for LICENSE

.github/workflows/android-smoke-test-build.yml, .github/workflows/android-smoke-test-compile.yml, .github/workflows/android-smoke-test-run.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/ios-smoke-test-build.yml, .github/workflows/ios-smoke-test-compile.yml, .github/workflows/ios-smoke-test-run.yml, .github/workflows/smoke-test-create.yml, scripts/smoke-test-ios.ps1
Addresses the first part of https://github.com/getsentry/sentry-unity/issues/1975
This separates the jobs that were targeting multiple platforms into individual workflows, responsible for a singular purpose. I.e. 
1. `platform-smoke-test-build`
2. `platform-smoke-test-compile`
3. `platform-smoke-test-run`
The restructuring of jobs also netted a nice speed increase from `55` down to about `30` minutes.
I.e. 
- Creating the empty smoke test project right from the beginning
- Having the job that installs the sentry package go through all of the setup required and then only wait for the UPM to be available to download while the SDK is building.
=> feat: Separate CI jobs into workflows

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
Previously, this was only applying to Android.
=> feat: Propagate `--allow-failure` to all platforms

src/Sentry.Unity.Editor/ConfigurationWindow/EnrichmentTab.cs, src/Sentry.Unity/Integrations/UnityApplicationLoggingIntegration.cs, src/Sentry.Unity/ScriptableSentryUnityOptions.cs, src/Sentry.Unity/SentryUnityOptions.cs
Currently, the SDK captures any logs sent with `Debug.LogError` as an event. There are some ways to mitigate this, such as by using a `BeforeSend` callback, but the filtering risks over (or under) filtration, and isn't completely clear on how to accomplish this. 
Since there are already options to enable/disable breadcrumb capturing, I've added one to enable/disable the functionality for events too.
=> Feat: Adds an option to disable capturing Debug.LogError as events

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/EnrichmentTab.cs, test/Sentry.Unity.Tests/UnityApplicationLoggingIntegrationTests.cs
Followup for https://github.com/getsentry/sentry-unity/pull/2009
- Facelifted for the presentation on the Enrichment tab
- Added changelog entry
- Updated test
=> chore: Changelog and tests for `Debug.LogError` flag

CHANGELOG.md, Directory.Build.targets
I currently can't build this because my Unity installations are in a custom install path managed by the Unity Hub, so I added some logic for supporting that setting in the `FindUnity` target.
Users can set a custom install path for Unity installations in the Unity Hub, and that information is recorded in a json file in the hub config folder. Older versions of the Hub also recorded a preferred version of Unity to be used, which can be used as a fallback if the requested version isn't available.
This adds support for finding Unity installations in this custom location, and for picking the latest (or preferred, if available) version of Unity that's installed, if the requested one isn't found. The error is changed to output all of the calculated paths that were scanned, instead of hardcoding …
=> Add support for finding Unity in the Hub alternate install path

CHANGELOG.md, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
Moves the debug symbols upload into a `finally` so it's done regardless of what happens with the native support handling.
Also adds cases to upload win32 debug files and the `*.pdb` files from MacOS Mono builds.
=> Add debug symbol uploads for Win32 and MacOS Mono builds

src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
Followup on https://github.com/getsentry/sentry-unity/pull/2021
In this PR I
- Moved option validation outside of `try-catch` block to bail early
- Symbol upload now happens regardless of native-support settings - to provide line numbers
- Improved logging
=> fix: Desktop symbol upload

CHANGELOG.md, src/Sentry.Unity.Editor/Android/AndroidManifestConfiguration.cs, test/Sentry.Unity.Editor.Tests/Android/AndroidManifestConfigurationTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1847
These changes make sure that the SDK now overwrites the Android SDK in the generated gradle project - if already present.
=> fix: Overwrite Android SDK during build

CHANGELOG.md, src/Sentry.Unity/Integrations/AnrIntegration.cs
Fixes https://github.com/getsentry/sentry-unity/issues/2042
=> fix: Fixed race condition in ANR Integration

Directory.Build.targets
This made it into the `.targets` with the v8 Java SDK update and was used during the bump. It's not used and does not do anything.
=> chore: Removed unused target

CHANGELOG.md, src/Sentry.Unity/SentryUnity.cs, src/Sentry.Unity/SentryUnitySDK.cs, test/Sentry.Unity.Tests/SentryUnityTests.cs
This PR adds a method `GetLastRunState` to the SentryUnity API to allow users to access whether the SDK detects a crash in the game's previous run.
Sample-Usage:
```
public class CrashDetector : MonoBehaviour
{
void Start()
{
// This assumes that the SDK is already initialized. 
// The SDK has already set up the native scope sync - it will return `Unknown` otherwise
var lastRunState = SentryUnity.CrashedLastRun();
switch (lastRunState)
{
case SentryUnity.LastRunState.Crashed:
Debug.Log("The application crashed during the previous run");
// Perform recovery actions or show user message.
break;
case SentryUnity.LastRunState.DidNotCrash:
Debug.Log("The previous run terminated normally");
break;
case SentryUnity.LastRunState.Unknown:
// The SDK was either not initialized or does not have …
```
=> feat: Added `GetLastRunState` to the SentryUnity

CHANGELOG.md, src/Sentry.Unity/Integrations/ISceneManager.cs, src/Sentry.Unity/Integrations/UnityScopeIntegration.cs, src/Sentry.Unity/Protocol/Unity.cs, test/Sentry.Unity.Tests/Protocol/UnityTests.cs, test/Sentry.Unity.Tests/SceneManagerIntegrationTests.cs, test/Sentry.Unity.Tests/UnityEventScopeTests.cs
Relates to https://github.com/getsentry/sentry-unity/issues/2073
Adds the active scene's name to the Unity context.
=> feat: Added active scene's name to unity context

CHANGELOG.md, src/Sentry.Unity/Integrations/UnityScopeIntegration.cs, test/Sentry.Unity.Tests/UnityEventScopeTests.cs
Adding the game's name to the app context. This should be especially helpful in case of UaaL.
=> feat: Adding the game's name to the app context

.github/workflows/android-smoke-test-run.yml, scripts/smoke-test-android.ps1, test/Scripts.Integration.Test/integration-test.ps1
I'm not exactly sure when or with which version this changes but the crash log switches between 
```
terminating with uncaught exception of type char const*
``` 
and 
```
terminating due to uncaught exception of type char const*
```
Replacing the `with` with `due to`.
Instead of relying on the exact wording from the logs from somewhere within Unity, we're relying on the ones from `sentry-native` (so we can blame ourselves if this breaks in the future).
With the separation into workflows in https://github.com/getsentry/sentry-unity/pull/1989 we're also no longer exporting a Gradle project that we're then building in a dedicated step. The `IsIntegrationTest` is a remnant from there.
=> fix: Android device crash tests

CHANGELOG.md, package-dev/Plugins/macOS/SentryNativeBridge.m
This bug got introduced with https://github.com/getsentry/sentry-unity/pull/1924
The iOS bridge received an update to report back the success of calling init. This was missing on the macOS bridge. The SDK still gets initialized and it captures crashes, but the scope sync is missing.
I'll address the missing integration tests as part or follow up on https://github.com/getsentry/sentry-unity/issues/2099
=> fix: Return success during Cocoa SDK init on macOS

.github/workflows/sdk.yml
After merging #2118, the [first job](https://github.com/getsentry/sentry-unity/actions/runs/14514115192/job/40719231256) in the main branch failed like this:
- Installing Linux Dependencies
```
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to dot.net:443 
```
- Build
```
/__w/_temp/997abeb5-d2d0-41eb-ad62-073478c13323.sh: 2: dotnet: not found
```
This tweak makes it more robust by a) allowing curl to retry a few times should there be any network hiccups, and b) ensuring the dependency installation step fails as appropriate instead of quietly ignoring the error and proceeding to the build step.
=> fix: retry curl dotnet-install.sh

.github/workflows/ios-smoke-test-compile.yml
The build currently takes `~10` minutes and fails due to timeouts. There was no special reasoning behind `10` minutes other than "fail faster" when updating the action last.
=> chore: Increase smoke test build timeout for iOS

CHANGELOG.md, package-dev/Plugins/Android/proguard-sentry-unity.pro
Propagating the trace ID fails otherwise.
=> fix: Updated `proguard.cfg`

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/danger.yml, .github/workflows/format-code.yml, .github/workflows/release.yml, .github/workflows/sdk.yml, .github/workflows/smoke-test-build-android.yml, .github/workflows/smoke-test-build-ios.yml, .github/workflows/smoke-test-compile-ios.yml, .github/workflows/smoke-test-create.yml, .github/workflows/smoke-test-run-android.yml, .github/workflows/smoke-test-run-ios.yml, .github/workflows/update-deps.yml
This fixes the messy list of available workflows on the Actions tab by giving each workflow an appropriate name.
=> chore: Name CI workflows

CHANGELOG.md, src/Sentry.Unity.Editor/ConfigurationWindow/DebugSymbolsTab.cs, src/Sentry.Unity.Editor/ConfigurationWindow/SentryWindow.cs, src/Sentry.Unity.Editor/ConfigurationWindow/Wizard.cs, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs, src/Sentry.Unity.Editor/SentryCli.cs, src/Sentry.Unity/SentryCliOptions.cs, test/Sentry.Unity.Editor.Tests/SentryCliTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/2058
This PR made the SDK respect `Organisation tokens`. Users using the the wizard going forward, won't have the `Organisation` set on the options as the org-slug will be taken from the embeddings of the token.
In case on non-organisation tokens (i.e. user tokens), the organisation can still be provided and will be used.
The relevant changes to tokens and sentry-cli are
- https://github.com/getsentry/rfcs/pull/91
- https://github.com/getsentry/sentry-cli/pull/1673
=> fix: `Organisation` no longer required for Sentry CLI options

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs, test/Sentry.Unity.Editor.iOS.Tests/SentryXcodeProjectTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/2057
In my opinion, this flag is supposed to allow users to unblock themselves. I.e. automated build systems somewhere, local dev environment and is accessible via the configure cli options callback. 
Since the user explicitly opted in to ignoring CLI errors, I think it's fine to simply log into a file.
The difference might seem minor but the build no longer errors with 
```
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
```
Before:
After:
=> fix: Ignor CLI errors when targeting `iOS`

CHANGELOG.md, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
Previously, everything was `info`. Now, the logged levels correspond with the actual level and respect the verbosity set in the options.
=> fix: Fixed sentry-cli logging levels when building for Desktop

test/Scripts.Integration.Test/Editor/Builder.cs
Relates to:
* https://github.com/getsentry/sentry-unity/issues/249
=> fix: Set stripping level in CI

CHANGELOG.md, src/Sentry.Unity.Editor.iOS/BuildPostProcess.cs, src/Sentry.Unity.Editor.iOS/SentryXcodeProject.cs, test/Sentry.Unity.Editor.iOS.Tests/BuildPostProcessorTests.cs, test/Sentry.Unity.Editor.iOS.Tests/SentryXcodeProjectTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/1973
There are a couple of limitations with the [PBXProject API](https://docs.unity3d.com/6000.0/Documentation/ScriptReference/iOS.Xcode.PBXProject.html), namely the ability to remove or overwrite an existing shell script in the build phase. When building via `append` this caused CLI options to not get copied over and respected by Xcode.
Instead of hardcoding arguments the shell script is now controlled by build settings that can be modified when building.
=> fix: `Append` builds for iOS respect CLI option changes

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/format-code.yml, .github/workflows/release.yml, .github/workflows/sdk.yml, .github/workflows/smoke-test-build-android.yml, .github/workflows/smoke-test-build-ios.yml, .github/workflows/smoke-test-compile-ios.yml, .github/workflows/smoke-test-create.yml, .github/workflows/smoke-test-run-android.yml, .github/workflows/smoke-test-run-ios.yml, .github/workflows/update-deps.yml
- Running these workflows is gated pretty well, but this mitigates the potential for a script injection attack by passing the input to an intermediary environment variable first.
- See https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack for more details.
- Using version tags or no specifier at all can open us up to dependency attacks. Pinning the SHA is a strong mitigation. 
- See: https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
=> ci: use envs in GHAs and pin versions

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md
@stephanie-anderson noted that the default labels from our issue templates in `sentry-dotnet` are no longer conforming with our current usage:
- see getsentry/sentry-dotnet#4270
This PR changes the default labels of `sentry-unity`'s _Issue Templates_ equivalently.
=> meta: fix default labels of issue templates

CHANGELOG.md, src/Sentry.Unity.Android/SentryJava.cs, test/Sentry.Unity.Android.Tests/SentryJavaTests.cs, test/Sentry.Unity.Tests/Stubs/TestHub.cs
Basically a followup on the scope sync changes in https://github.com/getsentry/sentry-unity/pull/2107
Fixes https://github.com/getsentry/sentry-unity/issues/2164
The issue originates from the following scenario:
1. User/plugin code runs on a background thread
2. That thread attaches to the JVM to do some work
3. It triggers a scope sync
4. We end up in the SDK, on the same thread
5. Since it's not on the main thread it attaches/detaches for the scope sync with the Android SDK
6. The thread executing user/plugin code was detached prematurely, causing a crash with `attempting to detach while still running code`
Since we cannot verify whether the current thread is already attached or not we "have" to do the scope sync on a thread we actually control, so we can safely attach/detach.  We …
=> fix: Safe Execute on JVM

.github/workflows/build.yml
Running [`Assembly Alias`](https://github.com/getsentry/dotnet-assembly-alias) currently fails in CI. This is due to .NET 6 not being available anymore and the tool targeting .NET 6 specifically.
```
The following frameworks were found:
8.0.18 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
9.0.4 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
9.0.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
To unblock ourselves we make use of [`--allow-rollforward`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install). Ideally, this would be done by the package itself. See https://github.com/getsentry/dotnet-assembly-alias/issues/20
=> fix: Roll forward for `Assembly Alias`

scripts/repack.ps1
I'm running repack to manually update the `.snapshot` and it keeps getting stuck if the `package-release` stuff already exists. Well, not any longer it doesn't!
=> chore: Clean `package-release` before repacking

package-dev/Runtime/SentryInitialization.cs, src/Sentry.Unity.Android/SentryNativeAndroid.cs, src/Sentry.Unity/NativeUtils/SentryPlatformServices.cs, src/Sentry.Unity/SentrySdk.cs, src/Sentry.Unity/SentryUnitySdk.cs, test/Sentry.Unity.Tests/ContextWriterTests.cs
Fixes https://github.com/getsentry/sentry-unity/issues/2247
Since the native configuration now gets called from within the SDK it does not need to be pulled out into `Android.Configure` and can universally be the first thing the SDK does.
This works because Init is getting automatically called in `SentryInitialization.cs` https://github.com/getsentry/sentry-unity/blob/c46352d4a286e22e6e1fef6d84a2a69fc77e2cd7/package-dev/Runtime/SentryInitialization.cs#L58-L71
=> fix: Collect `MainThreadData` first thing in `Init`

CHANGELOG.md, src/Sentry.Unity/SentryUnityOptions.cs
Fixes https://github.com/getsentry/sentry-unity/issues/2269
The SDK should mark known third party tools and libraries to `InAppExclude` so that the stacktrace highlights the really relevant bits - the user's code.
**Before:**
**After:**
**Before:**
**After:**
=> feat: Added `Cysharp` and `DG.Tweening` to `InAppExclude`

CHANGELOG.md, samples/unity-of-bugs/Assets/Scenes/1_BugFarm.unity, samples/unity-of-bugs/Assets/Scripts/BugFarmButtons.cs, src/Sentry.Unity.Editor/Native/BuildPostProcess.cs
Resolves https://github.com/getsentry/sentry-unity/issues/656, https://github.com/getsentry/sentry-unity/issues/1602
With this change Sentry CLI will now pick up debug symbols from within `Burst` and `_DoNotShip` directories automatically.
=> fix: Update debug symbol upload for Desktop

.github/workflows/ci.yml
The hub changed the message printed when prompted to return installed editor versions. This bump contains the fix.
=> fix: Fixed `setup-unity` in CI

CHANGELOG.md, src/Sentry.Unity/Integrations/AnrIntegration.cs, test/Sentry.Unity.Tests/AnrDetectionTests.cs, test/Sentry.Unity.Tests/AnrIntegrationTests.cs
The ANR (Application Not Responding) detection system was reporting false positives when Unity applications lose and regain focus with "Run In Background" disabled.
1. Uncheck "Run In Background" in Unity Project Settings
2. Start the application with ANR detection enabled
3. Application loses focus (e.g., user switches to another window)
4. Unity sets Application.runInBackground = false and pauses the application
5. Time continues to elapse while app is paused
6. Application regains focus and resumes
7. ANR watchdog checks elapsed time and incorrectly detects an ANR
8. False positive ANR event gets reported to Sentry
The single-threaded ANR detection implementation (`AnrWatchDogSingleThreaded`) uses timestamp-based monitoring via a coroutine. When the application is paused, the coroutine …
=> fix: Fixed false positive ANR events on `WebGL`

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/create-unity-matrix.yml
The current CI workflow tests all Unity versions (2021.3, 2022.3, 6000.0, 6000.1) across all platforms for every pull request. With only so many build server licenses, if there are multiple PRs they start blocking each other.
Minor annoyance that I ran into again when dropping support for Unity 2020: We've got the versions to test in a whole lot of different place. Ideally, this would be unified somewhere.
Split versions to be tested in 3 groups:
- `main` branch: Test everything: `2021`, `2022`, `6.0`, `6.1`. We'll need to look into `6.2` in the near future.
- `PR` branch: Test against the highest impacted versions: `2022`, `6.0`. We don't have any `#ifdef` as part of the initialization anymore, making this much saver.
- `Release` branches: Keep as is, a sanity check
Come up with a …
=> chore: Update Unity versions in CI 

.github/workflows/build.yml, .github/workflows/format-code.yml, global.json
Pinning the the SDK version so `dotnet` doesn't just take whatever is there.
=> chore: Pin SDK version
